using Domain.Assessment;
using Domain.Common;

namespace Domain.Reading;

/// <summary>
/// Aggregate root for a curated, CEFR-leveled reading passage (PROJECT-SPEC Faza 6 - the
/// Reading module: "darajalangan matn + interaktiv lug'at"). It owns an interactive
/// glossary (tap-to-translate vocabulary) and a set of comprehension questions. Like the
/// video catalog, the curated corpus is product content; the English body and questions
/// are authored, and all learner-facing Uzbek text is vetted (docs/development-guide.md rule 11).
/// </summary>
public sealed class ReadingPassage
{
    private readonly List<GlossaryEntry> _glossary = new();
    private readonly List<ReadingQuestion> _questions = new();

    // Parameterless ctor for EF Core materialization.
    private ReadingPassage()
    {
        Title = null!;
        Body = null!;
        Topic = null!;
        Category = null!;
    }

    private ReadingPassage(
        string title, string body, string topic, CefrLevel level, DateTimeOffset now)
    {
        Id = Guid.NewGuid();
        Title = title;
        Body = body;
        Topic = topic;
        Category = topic;
        Level = level;
        CreatedAt = now;
    }

    public Guid Id { get; private set; }

    /// <summary>
    /// The shared learning-spine topic this reading lesson teaches, when the passage was created
    /// for a topic (the topic-scoped lazy-fill path). Null for legacy stand-alone passages.
    /// </summary>
    public Guid? VocabularyTopicId { get; private set; }

    /// <summary>The passage title shown in the catalog and reader.</summary>
    public string Title { get; private set; }

    /// <summary>The full English text of the passage; empty until the lesson is filled.</summary>
    public string Body { get; private set; }

    /// <summary>Topic/tag used for curation and recommendation (e.g. "science").</summary>
    public string Topic { get; private set; }

    public string Category { get; private set; }

    public string? ContextGaps { get; private set; }

    /// <summary>The curated CEFR level of the passage.</summary>
    public CefrLevel Level { get; private set; }

    /// <summary>Pending until the body, glossary and questions are generated and cached.</summary>
    public ReadingPassageStatus Status { get; private set; } = ReadingPassageStatus.Filled;

    public DateTimeOffset CreatedAt { get; private set; }

    public IReadOnlyList<GlossaryEntry> Glossary => _glossary;
    public IReadOnlyList<ReadingQuestion> Questions => _questions;

    /// <summary>True once the lesson content has been generated and cached.</summary>
    public bool IsFilled => Status == ReadingPassageStatus.Filled;

    /// <summary>Number of words in the passage body (reader/level indicator).</summary>
    public int WordCount => Body.Split(
        new[] { ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries).Length;

    /// <summary>
    /// Builds a fully curated passage (level + glossary + questions known up front), as
    /// used by the seeded content catalog.
    /// </summary>
    public static ReadingPassage Curate(
        string title,
        string body,
        string topic,
        CefrLevel level,
        IEnumerable<GlossaryEntry> glossary,
        IEnumerable<ReadingQuestion> questions,
        DateTimeOffset now)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Passage title must not be empty.");
        if (string.IsNullOrWhiteSpace(body))
            throw new DomainException("Passage body must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Passage topic must not be empty.");

        var passage = new ReadingPassage(title.Trim(), body.Trim(), topic.Trim(), level, now);

        foreach (var entry in glossary)
        {
            if (entry is null)
                throw new DomainException("Glossary entry must not be null.");
            passage._glossary.Add(entry);
        }

        foreach (var question in questions)
        {
            if (question is null)
                throw new DomainException("Question must not be null.");
            passage._questions.Add(question);
        }

        return passage;
    }

    /// <summary>
    /// Creates a pending reading lesson bound to a learning-spine topic. The body, glossary and
    /// comprehension questions are generated by the LLM on first open and cached via
    /// <see cref="FillContent"/> - the same lazy-fill pattern as a vocabulary topic (rules 8, 10).
    /// </summary>
    public static ReadingPassage ForTopic(
        Guid vocabularyTopicId, string title, string topic, CefrLevel level, DateTimeOffset now)
    {
        if (vocabularyTopicId == Guid.Empty)
            throw new DomainException("A topic-scoped passage needs a vocabulary topic id.");
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Passage title must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Passage topic must not be empty.");

        return new ReadingPassage(title.Trim(), string.Empty, topic.Trim(), level, now)
        {
            VocabularyTopicId = vocabularyTopicId,
            Status = ReadingPassageStatus.Pending,
        };
    }

    /// <summary>
    /// Creates a pending, manually-curated passage from the admin catalog (metadata only; the body,
    /// glossary and questions are filled later). No learning-spine topic is bound.
    /// </summary>
    public static ReadingPassage CreateManual(
        string title, string topic, CefrLevel level, DateTimeOffset now)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Passage title must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Passage topic must not be empty.");

        return new ReadingPassage(title.Trim(), string.Empty, topic.Trim(), level, now)
        {
            VocabularyTopicId = null,
            Status = ReadingPassageStatus.Pending,
        };
    }

    /// <summary>
    /// Updates the passage's admin-editable metadata (title, topic, CEFR level).
    /// </summary>
    public void AdminUpdate(string title, string topic, CefrLevel level)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Passage title must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Passage topic must not be empty.");

        Title = title.Trim();
        Topic = topic.Trim();
        Level = level;
    }

    public void AdminReplaceContent(
        string title,
        string topic,
        string category,
        CefrLevel level,
        ReadingPassageStatus status,
        string body,
        string? contextGaps,
        IEnumerable<GlossaryEntry> glossary,
        IEnumerable<ReadingQuestion> questions)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Passage title must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Passage topic must not be empty.");
        if (string.IsNullOrWhiteSpace(category))
            throw new DomainException("Passage category must not be empty.");
        if (status == ReadingPassageStatus.Filled && string.IsNullOrWhiteSpace(body))
            throw new DomainException("A filled passage body must not be empty.");

        var glossaryList = glossary?.ToList() ?? throw new DomainException("Glossary must not be null.");
        var questionList = questions?.ToList() ?? throw new DomainException("Questions must not be null.");
        if (status == ReadingPassageStatus.Filled && questionList.Count == 0)
            throw new DomainException("A filled passage must have at least one comprehension question.");

        Title = title.Trim();
        Topic = topic.Trim();
        Category = category.Trim();
        Level = level;
        Status = status;
        Body = body.Trim();
        ContextGaps = string.IsNullOrWhiteSpace(contextGaps) ? null : contextGaps.Trim();

        _glossary.Clear();
        _glossary.AddRange(glossaryList);
        _questions.Clear();
        _questions.AddRange(questionList);
    }

    /// <summary>
    /// Stores the generated body, interactive glossary and comprehension questions, marking the
    /// lesson filled. Called once after the LLM produces the content; later reads serve the cache.
    /// </summary>
    public void FillContent(
        string body, IEnumerable<GlossaryEntry> glossary, IEnumerable<ReadingQuestion> questions)
    {
        if (string.IsNullOrWhiteSpace(body))
            throw new DomainException("Passage body must not be empty.");

        var questionList = questions?.ToList() ?? throw new DomainException("Questions must not be null.");
        if (questionList.Count == 0)
            throw new DomainException("A filled passage must have at least one comprehension question.");

        Body = body.Trim();

        _glossary.Clear();
        foreach (var entry in glossary ?? Enumerable.Empty<GlossaryEntry>())
            _glossary.Add(entry ?? throw new DomainException("Glossary entry must not be null."));

        _questions.Clear();
        foreach (var question in questionList)
            _questions.Add(question ?? throw new DomainException("Question must not be null."));

        Status = ReadingPassageStatus.Filled;
    }

    /// <summary>
    /// Grades a learner's answers. Questions with no submitted answer count as incorrect,
    /// so the score reflects the whole quiz (PROJECT-SPEC Faza 6 comprehension check).
    /// </summary>
    public ReadingQuizResult GradeQuiz(IReadOnlyDictionary<Guid, int> answers)
    {
        if (_questions.Count == 0)
            throw new DomainException("This passage has no comprehension questions.");

        var outcomes = new List<ReadingQuestionOutcome>(_questions.Count);
        foreach (var question in _questions)
        {
            var hasAnswer = answers.TryGetValue(question.Id, out var selected);
            if (!hasAnswer)
                selected = -1;

            outcomes.Add(new ReadingQuestionOutcome(
                question.Id,
                selected,
                question.CorrectOptionIndex,
                hasAnswer && question.IsCorrect(selected),
                question.HintCode,
                question.Explanation));
        }

        return new ReadingQuizResult(Id, _questions.Count, outcomes.Count(o => o.IsCorrect), outcomes);
    }
}
