using Domain.Assessment;
using Domain.Common;

namespace Domain.Vocabulary;

/// <summary>
/// Aggregate root for a curated vocabulary topic (PROJECT-SPEC module 4 - "Lug'at"). A topic
/// teaches words <i>in context</i>: it owns a short CEFR-leveled English passage and the set of
/// target words (15) that appear in it. The catalog is seeded as metadata only; the passage and
/// its words are generated by the LLM on first open and cached (rules 8, 10) - the same lazy-fill
/// pattern as video transcripts. The passage is the target language (English) so the model may
/// author it; each word's Uzbek meaning is the sanctioned translate-a-source path of rule 11.
/// </summary>
public sealed class VocabularyTopic
{
    /// <summary>How many target words a filled topic teaches (PROJECT-SPEC: 15 new words).</summary>
    public const int TargetWordCount = 20;

    /// <summary>
    /// The current content schema/generation version. Bumped whenever the generation recipe changes
    /// in a way that should re-fill already-cached topics. v0 = legacy noun-heavy content (no part of
    /// speech); v1 = balanced 4-way part-of-speech mix (verbs/nouns/adjectives/adverbs); v2 =
    /// level-adaptive 12-category plan (adds prepositions, pronouns, determiners and, from B1+, the
    /// multi-word chunks: phrasal verbs, collocations, idioms, expressions - see
    /// <see cref="TopicWordPlan"/>); v3 = real topic-specific passages from the Gemini request-path
    /// generator, replacing the deterministic Local stand-in's repetitive filler (which had polluted
    /// already-opened topics when no backfill had run). A topic whose <see cref="ContentVersion"/> is
    /// below this is refreshed on next backfill or first open (<see cref="NeedsContentRefresh"/>).
    /// </summary>
    public const int CurrentContentVersion = 4;

    /// <summary>Default number of cloze questions in the practice quiz.</summary>
    public const int DefaultQuizSize = 8;

    private const int OptionsPerQuestion = 4;

    private readonly List<TopicWord> _words = new();

    // Parameterless ctor for EF Core materialization.
    private VocabularyTopic()
    {
        Slug = null!;
        Title = null!;
        TitleUz = null!;
        Category = null!;
        GrammarFocusCode = null!;
        Passage = null!;
    }

    private VocabularyTopic(
        string slug, string title, string titleUz, string category, string grammarFocusCode,
        CefrLevel level, DateTimeOffset now, int sequence)
    {
        Id = Guid.NewGuid();
        Slug = slug;
        Title = title;
        TitleUz = titleUz;
        Category = category;
        GrammarFocusCode = grammarFocusCode;
        Sequence = sequence;
        Level = level;
        Passage = string.Empty;
        Status = VocabularyTopicStatus.Pending;
        CreatedAt = now;
    }

    public Guid Id { get; private set; }

    /// <summary>Stable, human-readable key (e.g. "a1-my-family"); seeds the deterministic quiz.</summary>
    public string Slug { get; private set; }

    /// <summary>The English topic title shown in the catalog and reader.</summary>
    public string Title { get; private set; }

    /// <summary>The vetted Uzbek topic label shown in the catalog (rule 11).</summary>
    public string TitleUz { get; private set; }

    /// <summary>Theme/tag used for grouping in the catalog (e.g. "daily_life").</summary>
    public string Category { get; private set; }

    /// <summary>
    /// The grammar point this topic teaches (e.g. "present-simple"). Across a level's 50 topics
    /// the focus codes cycle through that level's grammar syllabus, so the spine deterministically
    /// covers the CEFR grammar progression. The Grammar module (and its vetted Uzbek explanation
    /// templates, rule 11) resolve this code; it is taught in the topic's own context.
    /// </summary>
    public string GrammarFocusCode { get; private set; }

    /// <summary>
    /// The topic's position in its level's learning sequence (0-based). The catalog orders the 50
    /// topics so they follow the level's grammar progression - all topics teaching the first grammar
    /// point come first, then the second, and so on - so the spine reads as a coherent course. Every
    /// skill reads the shared spine in this order, keeping the six modules aligned.
    /// </summary>
    public int Sequence { get; private set; }

    public CefrLevel Level { get; private set; }

    /// <summary>The generated English passage; empty until the topic is filled.</summary>
    public string Passage { get; private set; }

    public VocabularyTopicStatus Status { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }

    /// <summary>
    /// The generation version of the cached content (see <see cref="CurrentContentVersion"/>). 0 for
    /// topics filled before parts of speech were tracked.
    /// </summary>
    public int ContentVersion { get; private set; }

    public IReadOnlyList<TopicWord> Words => _words;

    public bool IsFilled => Status == VocabularyTopicStatus.Filled;

    /// <summary>
    /// True when the topic still needs (re)generation: it has never been filled, or it was filled by
    /// an older recipe (<see cref="ContentVersion"/> below <see cref="CurrentContentVersion"/>) and
    /// should be refreshed to the current balanced part-of-speech mix.
    /// </summary>
    public bool NeedsContentRefresh => !IsFilled || ContentVersion < CurrentContentVersion;

    /// <summary>Builds a catalog topic carrying only its curated metadata (no passage yet).</summary>
    public static VocabularyTopic Curate(
        string slug, string title, string titleUz, string category, string grammarFocusCode,
        CefrLevel level, DateTimeOffset now, int sequence = 0)
    {
        if (string.IsNullOrWhiteSpace(slug))
            throw new DomainException("Topic slug must not be empty.");
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Topic title must not be empty.");
        if (string.IsNullOrWhiteSpace(titleUz))
            throw new DomainException("Topic Uzbek title must not be empty.");
        if (string.IsNullOrWhiteSpace(category))
            throw new DomainException("Topic category must not be empty.");
        if (string.IsNullOrWhiteSpace(grammarFocusCode))
            throw new DomainException("Topic grammar focus code must not be empty.");

        return new VocabularyTopic(
            slug.Trim(), title.Trim(), titleUz.Trim(), category.Trim(), grammarFocusCode.Trim(), level, now,
            sequence);
    }

    /// <summary>
    /// Refreshes the curated metadata (used by the catalog self-heal when a surviving topic's
    /// labels or grammar focus change between releases); the cached passage/words are untouched.
    /// </summary>
    public void UpdateMetadata(
        string title, string titleUz, string category, string grammarFocusCode, int sequence)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Topic title must not be empty.");
        if (string.IsNullOrWhiteSpace(titleUz))
            throw new DomainException("Topic Uzbek title must not be empty.");
        if (string.IsNullOrWhiteSpace(category))
            throw new DomainException("Topic category must not be empty.");
        if (string.IsNullOrWhiteSpace(grammarFocusCode))
            throw new DomainException("Topic grammar focus code must not be empty.");

        Title = title.Trim();
        TitleUz = titleUz.Trim();
        Category = category.Trim();
        GrammarFocusCode = grammarFocusCode.Trim();
        Sequence = sequence;
    }

    /// <summary>Sets the topic's CEFR level (used by admin metadata updates).</summary>
    public void SetLevel(CefrLevel level) => Level = level;

    /// <summary>
    /// Stores the generated passage and its target words, marking the topic filled. Called once
    /// after the LLM produces the content; subsequent reads serve the cached result.
    /// </summary>
    public void FillContent(string passage, IEnumerable<TopicWord> words)
    {
        if (string.IsNullOrWhiteSpace(passage))
            throw new DomainException("Topic passage must not be empty.");

        var list = words?.ToList() ?? throw new DomainException("Topic words must not be null.");
        if (list.Count == 0)
            throw new DomainException("A filled topic must have at least one target word.");

        Passage = passage.Trim();
        _words.Clear();
        _words.AddRange(list);
        Status = VocabularyTopicStatus.Filled;
        ContentVersion = CurrentContentVersion;
    }

    /// <summary>Replaces the persisted passage and word contexts from the admin editor.</summary>
    public void UpdateContent(string passage, IEnumerable<TopicWord> words)
    {
        FillContent(passage, words);
    }

    /// <summary>
    /// Builds the deterministic cloze quiz (PROJECT-SPEC B.1 "Matnda tanlash"). Each eligible
    /// target word (one whose example sentence contains it) yields a question: its sentence with
    /// the word blanked, and four options - the word plus distractors drawn from the topic's other
    /// words. Ordering is seeded by the slug so the quiz is reproducible across requests, which is
    /// what lets <see cref="GradeQuiz"/> grade a submission without persisting the questions.
    /// </summary>
    public IReadOnlyList<TopicQuizQuestion> BuildQuiz(int maxQuestions = DefaultQuizSize)
    {
        if (!IsFilled)
            throw new DomainException("Cannot build a quiz for a topic that has not been filled.");

        var eligible = _words
            .Where(w => w.ExampleSentence is not null && Contains(w.ExampleSentence!, w.Word))
            .ToList();

        // Distractors need at least a few distinct words to choose from; otherwise no quiz.
        if (_words.Count < OptionsPerQuestion)
            return Array.Empty<TopicQuizQuestion>();

        var rng = new Random(SeedFromSlug(Slug));
        var questions = new List<TopicQuizQuestion>();

        foreach (var word in eligible.Take(maxQuestions))
        {
            var others = _words
                .Where(w => !string.Equals(w.Word, word.Word, StringComparison.OrdinalIgnoreCase))
                .DistinctBy(w => w.Word, StringComparer.OrdinalIgnoreCase)
                .ToList();

            // Prefer distractors of the same part of speech (a verb gap gets verb options) so the
            // choice tests meaning, not grammar; top up from the rest when too few share the class.
            var sameClass = others
                .Where(w => w.PartOfSpeech != PartOfSpeech.Other && w.PartOfSpeech == word.PartOfSpeech)
                .OrderBy(_ => rng.Next())
                .Select(w => w.Word);
            var rest = others
                .Where(w => !(w.PartOfSpeech != PartOfSpeech.Other && w.PartOfSpeech == word.PartOfSpeech))
                .OrderBy(_ => rng.Next())
                .Select(w => w.Word);

            var distractors = sameClass.Concat(rest)
                .Take(OptionsPerQuestion - 1)
                .ToList();

            if (distractors.Count < OptionsPerQuestion - 1)
                continue;

            var options = distractors.Append(word.Word).OrderBy(_ => rng.Next()).ToList();
            var correctIndex = options.FindIndex(o => string.Equals(o, word.Word, StringComparison.OrdinalIgnoreCase));

            questions.Add(new TopicQuizQuestion(
                questions.Count, word.Word, Blank(word.ExampleSentence!, word.Word), options, correctIndex));
        }

        return questions;
    }

    /// <summary>
    /// Grades a submission. Answers are keyed by question index; an unanswered question counts
    /// as incorrect, so the score reflects the whole quiz.
    /// </summary>
    public TopicQuizResult GradeQuiz(IReadOnlyDictionary<int, int> answers, int maxQuestions = DefaultQuizSize)
    {
        var quiz = BuildQuiz(maxQuestions);
        if (quiz.Count == 0)
            throw new DomainException("This topic has no quiz questions.");

        var outcomes = new List<TopicQuizOutcome>(quiz.Count);
        foreach (var q in quiz)
        {
            var hasAnswer = answers.TryGetValue(q.Index, out var selected);
            if (!hasAnswer)
                selected = -1;

            outcomes.Add(new TopicQuizOutcome(
                q.Index, q.Word, selected, q.CorrectOptionIndex, hasAnswer && q.IsCorrect(selected)));
        }

        return new TopicQuizResult(Id, quiz.Count, outcomes.Count(o => o.IsCorrect), outcomes);
    }

    private static bool Contains(string sentence, string word) =>
        sentence.IndexOf(word, StringComparison.OrdinalIgnoreCase) >= 0;

    private static string Blank(string sentence, string word)
    {
        var idx = sentence.IndexOf(word, StringComparison.OrdinalIgnoreCase);
        return idx < 0
            ? sentence
            : string.Concat(sentence.AsSpan(0, idx), TopicQuizQuestion.Blank, sentence.AsSpan(idx + word.Length));
    }

    // Stable, cross-process hash of the slug (FNV-1a). Random.GetHashCode would not be
    // stable across restarts, so quiz option ordering must not depend on it.
    private static int SeedFromSlug(string slug)
    {
        unchecked
        {
            const uint offset = 2166136261;
            const uint prime = 16777619;
            var hash = offset;
            foreach (var c in slug)
            {
                hash ^= c;
                hash *= prime;
            }

            return (int)hash;
        }
    }
}
