export type AuditAudience = "public" | "new-user" | "onboarding" | "goal" | "learner" | "admin";
export type AuditRouteKind = "page" | "redirect" | "legacy";

export interface AuditRoute {
  pattern: string;
  path: string;
  audience: AuditAudience;
  kind?: AuditRouteKind;
  focus?: boolean;
  expectedText?: string;
}

export const AUDIT_IDS = {
  topic: "11111111-1111-1111-1111-111111111111",
  book: "b1111111-1111-4111-8111-111111111111",
  bookSection: "s1111111-1111-4111-8111-111111111111",
  video: "v1111111-1111-4111-8111-111111111111",
  playlist: "PLb9HBx1ySEwTUAwQCM_7GbBebp9nV0cmU",
  adminUser: "u1111111-1111-4111-8111-111111111111",
  adminVocabulary: "a1111111-1111-1111-1111-111111111111",
  adminGrammar: "g1111111-1111-4111-8111-111111111111",
  adminListening: "l1111111-1111-4111-8111-111111111111",
  adminReading: "r1111111-1111-4111-8111-111111111111",
  leaderboardLearner: "11111111-1111-4111-8111-111111111112",
} as const;

export const AUDIT_ROUTES: AuditRoute[] = [
  { pattern: "/", path: "/", audience: "public", expectedText: "EnglishAI" },
  { pattern: "/landing", path: "/landing", audience: "public", expectedText: "EnglishAI" },
  { pattern: "/landing/eng", path: "/LANDING/eng", audience: "public", expectedText: "Knowing is good." },
  { pattern: "/en/", path: "/en/", audience: "public", expectedText: "EnglishAI" },
  { pattern: "/ingliz-tilini-organish", path: "/ingliz-tilini-organish", audience: "public", expectedText: "o‘rganing" },
  { pattern: "/en/learn-english", path: "/en/learn-english", audience: "public", expectedText: "Learn English" },
  { pattern: "/ai-ingliz-tutor", path: "/ai-ingliz-tutor", audience: "public", expectedText: "AI" },
  { pattern: "/en/ai-english-tutor", path: "/en/ai-english-tutor", audience: "public", expectedText: "AI" },
  { pattern: "/vocabulary", path: "/vocabulary", audience: "public", expectedText: "so‘z" },
  { pattern: "/en/vocabulary", path: "/en/vocabulary", audience: "public", expectedText: "vocabulary" },
  { pattern: "/grammar", path: "/grammar", audience: "public", expectedText: "Grammatika" },
  { pattern: "/en/grammar", path: "/en/grammar", audience: "public", expectedText: "grammar" },
  { pattern: "/cefr", path: "/cefr", audience: "public", expectedText: "CEFR" },
  { pattern: "/en/cefr", path: "/en/cefr", audience: "public", expectedText: "CEFR" },
  { pattern: "/ielts", path: "/ielts", audience: "public", expectedText: "IELTS" },
  { pattern: "/en/ielts", path: "/en/ielts", audience: "public", expectedText: "IELTS" },
  { pattern: "/speaking/*", path: "/speaking/legacy", audience: "public", kind: "redirect" },
  { pattern: "/vocabulary/*", path: "/vocabulary/legacy", audience: "public", kind: "redirect" },
  { pattern: "/grammar/*", path: "/grammar/legacy", audience: "public", kind: "redirect" },
  { pattern: "/learn", path: "/learn", audience: "public", expectedText: "Qo‘llanmalar" },
  { pattern: "/learn/:slug", path: "/learn/ai-bilan-ingliz-tilini-organish", audience: "public", expectedText: "AI" },
  { pattern: "/methodology", path: "/methodology", audience: "public", expectedText: "metod" },
  { pattern: "/about", path: "/about", audience: "public", expectedText: "EnglishAI" },
  { pattern: "/pricing", path: "/pricing", audience: "public", expectedText: "Bepul" },
  { pattern: "/product", path: "/product", audience: "public", expectedText: "EnglishAI mahsuloti" },
  { pattern: "/contact", path: "/contact", audience: "public", expectedText: "Aloqa" },
  { pattern: "/editorial-policy", path: "/editorial-policy", audience: "public", expectedText: "Tahrir" },
  { pattern: "/login", path: "/login", audience: "public" },
  { pattern: "/hero", path: "/hero", audience: "public" },
  { pattern: "/dev/onboarding/:page", path: "/dev/onboarding/username", audience: "public" },
  { pattern: "/username", path: "/username", audience: "new-user", focus: true },
  { pattern: "/onboarding/profile-details", path: "/onboarding/profile-details", audience: "new-user", focus: true },
  { pattern: "/onboarding/goal", path: "/onboarding/goal", audience: "goal", focus: true },
  { pattern: "/welcome", path: "/welcome", audience: "onboarding", focus: true },
  { pattern: "/assessment", path: "/assessment", audience: "onboarding", focus: true },
  { pattern: "/placement", path: "/placement", audience: "onboarding", focus: true },
  { pattern: "/placement/result", path: "/placement/result", audience: "onboarding", focus: true },
  { pattern: "/levels/exit-test", path: "/levels/exit-test", audience: "learner", focus: true },
  { pattern: "/levels/exit-test/result", path: "/levels/exit-test/result", audience: "learner", focus: true },
  { pattern: "/home", path: "/home", audience: "learner", expectedText: "Salom," },
  { pattern: "/levels", path: "/levels", audience: "learner" },
  { pattern: "/app/speaking", path: "/app/speaking", audience: "learner" },
  { pattern: "/app/speaking/topics", path: "/app/speaking/topics", audience: "learner" },
  { pattern: "/app/speaking/free", path: "/app/speaking/free", audience: "learner", focus: true },
  { pattern: "/app/speaking/topic/:topicId", path: `/app/speaking/topic/${AUDIT_IDS.topic}`, audience: "learner", focus: true },
  { pattern: "/app/speaking/free-talk", path: "/app/speaking/free-talk", audience: "learner" },
  { pattern: "/app/speaking/free-talk/:topicCode", path: "/app/speaking/free-talk/my_family", audience: "learner", focus: true },
  { pattern: "/app/speaking/role-talk", path: "/app/speaking/role-talk", audience: "learner", expectedText: "Ish suhbati" },
  { pattern: "/app/speaking/role-talk/:scenarioCode", path: "/app/speaking/role-talk/airport_check_in", audience: "learner", focus: true },
  { pattern: "/app/speaking/live-tutor/:tutorId", path: "/app/speaking/live-tutor/american", audience: "learner", focus: true },
  { pattern: "/app/speaking/roleplay", path: "/app/speaking/roleplay", audience: "learner", kind: "redirect" },
  { pattern: "/app/speaking/pronunciation/:word", path: "/app/speaking/pronunciation/world", audience: "learner", focus: true },
  { pattern: "/app/speaking/practice-words", path: "/app/speaking/practice-words", audience: "learner", focus: true },
  { pattern: "/pronounciation/:word", path: "/pronounciation/world", audience: "learner", kind: "legacy" },
  { pattern: "/video", path: "/video", audience: "learner", expectedText: "English Conversation for Beginners" },
  { pattern: "/video/search", path: "/video/search?q=Puss%20in%20Boots", audience: "learner", focus: true },
  { pattern: "/video/playlists/:playlistId", path: `/video/playlists/${AUDIT_IDS.playlist}`, audience: "learner", focus: true },
  { pattern: "/video/playlists/:playlistId/:episodeNumber", path: `/video/playlists/${AUDIT_IDS.playlist}/01`, audience: "learner", focus: true },
  { pattern: "/video/playlist/:playlistId", path: `/video/playlist/${AUDIT_IDS.playlist}`, audience: "learner", focus: true },
  { pattern: "/video/:id/play", path: `/video/${AUDIT_IDS.video}/play`, audience: "learner", focus: true },
  { pattern: "/video/:id/quiz", path: `/video/${AUDIT_IDS.video}/quiz`, audience: "learner", focus: true },
  { pattern: "/reading", path: "/reading", audience: "learner", expectedText: "Salomlashuv va tanishuv" },
  { pattern: "/books", path: "/books", audience: "learner", expectedText: "A New Friend" },
  { pattern: "/books/:bookId", path: `/books/${AUDIT_IDS.book}`, audience: "learner", focus: true },
  { pattern: "/books/:bookId/sections/:sectionId", path: `/books/${AUDIT_IDS.book}/sections/${AUDIT_IDS.bookSection}`, audience: "learner", kind: "redirect" },
  { pattern: "/app/grammar", path: "/app/grammar", audience: "learner", expectedText: "Present Simple" },
  { pattern: "/app/grammar/topic/:topicId", path: `/app/grammar/topic/${AUDIT_IDS.topic}`, audience: "learner", focus: true },
  { pattern: "/listening/topic/:topicId", path: `/listening/topic/${AUDIT_IDS.topic}`, audience: "learner", focus: true },
  { pattern: "/reading/topic/:topicId", path: `/reading/topic/${AUDIT_IDS.topic}`, audience: "learner", focus: true },
  { pattern: "/writing/topic/:topicId", path: `/writing/topic/${AUDIT_IDS.topic}`, audience: "learner", focus: true },
  { pattern: "/writing", path: "/writing", audience: "learner", expectedText: "Salomlashuv va tanishuv" },
  { pattern: "/writing/task/:topicId", path: `/writing/task/${AUDIT_IDS.topic}`, audience: "learner", focus: true },
  { pattern: "/listening", path: "/listening", audience: "learner", expectedText: "Salomlashuv va tanishuv" },
  { pattern: "/notifications", path: "/notifications", audience: "learner", kind: "redirect" },
  { pattern: "/app/vocabulary", path: "/app/vocabulary", audience: "learner", kind: "redirect" },
  { pattern: "/app/vocabulary/topics", path: "/app/vocabulary/topics", audience: "learner", expectedText: "Salomlashuv va tanishuv" },
  { pattern: "/app/vocabulary/topic/:topicId", path: `/app/vocabulary/topic/${AUDIT_IDS.topic}`, audience: "learner", focus: true },
  { pattern: "/app/vocabulary/topic/:topicId/pronunciation/:wordIndex", path: `/app/vocabulary/topic/${AUDIT_IDS.topic}/pronunciation/0`, audience: "learner", focus: true },
  { pattern: "/app/vocabulary/review", path: "/app/vocabulary/review", audience: "learner", focus: true },
  { pattern: "/app/vocabulary/saved", path: "/app/vocabulary/saved", audience: "learner" },
  { pattern: "/app/vocabulary/saved/:topicId/practice", path: `/app/vocabulary/saved/${AUDIT_IDS.topic}/practice`, audience: "learner", focus: true },
  { pattern: "/progress", path: "/progress", audience: "learner" },
  { pattern: "/leaderboard", path: "/leaderboard", audience: "learner", expectedText: "Demo" },
  { pattern: "/leaderboard/:learnerId", path: `/leaderboard/${AUDIT_IDS.leaderboardLearner}`, audience: "learner" },
  { pattern: "/profile", path: "/profile", audience: "learner", expectedText: "demo@englishai.uz" },
  { pattern: "/support", path: "/support", audience: "learner", expectedText: "Support" },
  { pattern: "/admin", path: "/admin", audience: "admin" },
  { pattern: "/admin/curriculum", path: "/admin/curriculum", audience: "admin" },
  { pattern: "/admin/users", path: "/admin/users", audience: "admin", expectedText: "Demo Admin" },
  { pattern: "/admin/support", path: "/admin/support", audience: "admin", expectedText: "Support" },
  { pattern: "/admin/users/:userId", path: `/admin/users/${AUDIT_IDS.adminUser}`, audience: "admin" },
  { pattern: "/admin/vocabulary", path: "/admin/vocabulary", audience: "admin" },
  { pattern: "/admin/vocabulary-images", path: "/admin/vocabulary-images", audience: "admin" },
  { pattern: "/admin/vocabulary/:id/edit", path: `/admin/vocabulary/${AUDIT_IDS.adminVocabulary}/edit`, audience: "admin" },
  { pattern: "/admin/grammar", path: "/admin/grammar", audience: "admin" },
  { pattern: "/admin/grammar/:id/edit", path: `/admin/grammar/${AUDIT_IDS.adminGrammar}/edit`, audience: "admin" },
  { pattern: "/admin/listening", path: "/admin/listening", audience: "admin" },
  { pattern: "/admin/listening/:id/edit", path: `/admin/listening/${AUDIT_IDS.adminListening}/edit`, audience: "admin" },
  { pattern: "/admin/reading", path: "/admin/reading", audience: "admin" },
  { pattern: "/admin/reading/:id/edit", path: `/admin/reading/${AUDIT_IDS.adminReading}/edit`, audience: "admin" },
  { pattern: "/admin/metrics", path: "/admin/metrics", audience: "admin" },
  { pattern: "/admin/notifications", path: "/admin/notifications", audience: "admin" },
  { pattern: "/admin/sections", path: "/admin/sections", audience: "admin" },
  { pattern: "/admin/server", path: "/admin/server", audience: "admin" },
  { pattern: "*", path: "/route-that-does-not-exist", audience: "public" },
];
