using Domain.Assessment;
using Domain.Common;

namespace Domain.Listening;

/// <summary>
/// Aggregate root for a curated, CEFR-leveled listening exercise (PROJECT-SPEC Faza 4 - the
/// Listening module). The learner hears short audio synthesized from <see cref="Transcript"/>
/// (Azure Neural TTS, cached per exercise so each clip is synthesized once - docs/development-guide.md rule
/// 10) and answers comprehension questions. The transcript is the authored English script and
/// is revealed only after answering, so the learner must rely on listening first. All
/// learner-facing Uzbek text is vetted (docs/development-guide.md rule 11).
/// </summary>
public sealed class ListeningExercise
{
    private readonly List<ListeningQuestion> _questions = new();
    private readonly List<ListeningSegment> _segments = new();

    // Parameterless ctor for EF Core materialization.
    private ListeningExercise()
    {
        Title = null!;
        Transcript = null!;
        Topic = null!;
    }

    private ListeningExercise(
        string title, string transcript, string topic, CefrLevel level, DateTimeOffset now)
    {
        Id = Guid.NewGuid();
        Title = title;
        Transcript = transcript;
        Topic = topic;
        Level = level;
        CreatedAt = now;
    }

    public Guid Id { get; private set; }

    /// <summary>
    /// The shared learning-spine topic this exercise teaches, when it was created for a topic (the
    /// topic-scoped lazy-fill path). Null for legacy stand-alone seeded exercises.
    /// </summary>
    public Guid? VocabularyTopicId { get; private set; }

    /// <summary>The exercise title shown in the catalog and player.</summary>
    public string Title { get; private set; }

    /// <summary>
    /// The English script that is synthesized to audio (and shown as the transcript after the
    /// learner answers). This is the spoken content of the clip.
    /// </summary>
    public string Transcript { get; private set; }

    /// <summary>Topic/tag used for curation and recommendation (e.g. "everyday").</summary>
    public string Topic { get; private set; }

    /// <summary>The curated CEFR level of the exercise.</summary>
    public CefrLevel Level { get; private set; }

    /// <summary>Pending until the transcript and questions are generated and cached (topic-scoped path).</summary>
    public ListeningExerciseStatus Status { get; private set; } = ListeningExerciseStatus.Filled;

    /// <summary>True once the transcript and questions have been generated and cached.</summary>
    public bool IsFilled => Status == ListeningExerciseStatus.Filled;

    public DateTimeOffset CreatedAt { get; private set; }

    public IReadOnlyList<ListeningQuestion> Questions => _questions;
    public IReadOnlyList<ListeningSegment> Segments => _segments;

    /// <summary>Number of words in the transcript (clip length indicator).</summary>
    public int WordCount => Transcript.Split(
        new[] { ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries).Length;

    /// <summary>
    /// Builds a fully curated exercise (level + transcript + questions known up front), as
    /// used by the seeded content catalog.
    /// </summary>
    public static ListeningExercise Curate(
        string title,
        string transcript,
        string topic,
        CefrLevel level,
        IEnumerable<ListeningQuestion> questions,
        DateTimeOffset now)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Exercise title must not be empty.");
        if (string.IsNullOrWhiteSpace(transcript))
            throw new DomainException("Transcript must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Exercise topic must not be empty.");

        var exercise = new ListeningExercise(title.Trim(), transcript.Trim(), topic.Trim(), level, now);

        foreach (var question in questions)
        {
            if (question is null)
                throw new DomainException("Question must not be null.");
            exercise._questions.Add(question);
        }

        if (exercise._questions.Count == 0)
            throw new DomainException("A listening exercise needs at least one question.");

        return exercise;
    }

    /// <summary>
    /// Creates a pending listening exercise bound to a learning-spine topic. Its transcript and
    /// comprehension questions are generated by the LLM on first open and cached via
    /// <see cref="FillContent"/> - the same lazy-fill pattern as a reading lesson (rules 8, 10). The
    /// clip is then synthesized from the transcript by Azure TTS and cached (rule 10).
    /// </summary>
    public static ListeningExercise ForTopic(
        Guid vocabularyTopicId, string title, string topic, CefrLevel level, DateTimeOffset now)
    {
        if (vocabularyTopicId == Guid.Empty)
            throw new DomainException("A topic-scoped exercise needs a vocabulary topic id.");
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Exercise title must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Exercise topic must not be empty.");

        return new ListeningExercise(title.Trim(), string.Empty, topic.Trim(), level, now)
        {
            VocabularyTopicId = vocabularyTopicId,
            Status = ListeningExerciseStatus.Pending,
        };
    }

    /// <summary>
    /// Builds a manually-curated PENDING listening exercise (admin CRUD path) with no transcript or
    /// questions yet, not bound to a learning-spine topic.
    /// </summary>
    public static ListeningExercise CreateManual(
        string title, string topic, CefrLevel level, DateTimeOffset now)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Exercise title must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Exercise topic must not be empty.");

        return new ListeningExercise(title.Trim(), string.Empty, topic.Trim(), level, now)
        {
            VocabularyTopicId = null,
            Status = ListeningExerciseStatus.Pending,
        };
    }

    /// <summary>
    /// Updates the admin-curated metadata (title, topic, CEFR level) of a listening exercise.
    /// </summary>
    public void AdminUpdate(string title, string topic, CefrLevel level)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Exercise title must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Exercise topic must not be empty.");

        Title = title.Trim();
        Topic = topic.Trim();
        Level = level;
    }

    public void AdminReplace(
        string title,
        string topic,
        CefrLevel level,
        ListeningExerciseStatus status,
        Guid? vocabularyTopicId,
        string transcript,
        IEnumerable<ListeningSegment> segments,
        IEnumerable<ListeningQuestion> questions)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Exercise title must not be empty.");
        if (string.IsNullOrWhiteSpace(topic))
            throw new DomainException("Exercise topic must not be empty.");

        var segmentList = segments?.ToList() ?? throw new DomainException("Segments must not be null.");
        var questionList = questions?.ToList() ?? throw new DomainException("Questions must not be null.");
        if (status == ListeningExerciseStatus.Filled && string.IsNullOrWhiteSpace(transcript))
            throw new DomainException("A filled listening exercise needs a transcript.");
        if (status == ListeningExerciseStatus.Filled && questionList.Count == 0)
            throw new DomainException("A filled listening exercise needs at least one question.");

        Title = title.Trim();
        Topic = topic.Trim();
        Level = level;
        Status = status;
        VocabularyTopicId = vocabularyTopicId;
        Transcript = transcript.Trim();
        _segments.Clear();
        _segments.AddRange(segmentList.OrderBy(segment => segment.Order));
        _questions.Clear();
        _questions.AddRange(questionList);
    }

    /// <summary>
    /// Stores the generated transcript and comprehension questions, marking the exercise filled.
    /// Called once after the LLM produces the content; later reads serve the cache.
    /// </summary>
    public void FillContent(string transcript, IEnumerable<ListeningQuestion> questions)
    {
        if (string.IsNullOrWhiteSpace(transcript))
            throw new DomainException("Transcript must not be empty.");

        var questionList = questions?.ToList() ?? throw new DomainException("Questions must not be null.");
        if (questionList.Count == 0)
            throw new DomainException("A filled exercise must have at least one comprehension question.");

        Transcript = transcript.Trim();

        _questions.Clear();
        foreach (var question in questionList)
            _questions.Add(question ?? throw new DomainException("Question must not be null."));

        Status = ListeningExerciseStatus.Filled;
    }

    /// <summary>
    /// Grades a learner's answers. Questions with no submitted answer count as incorrect, so
    /// the score reflects the whole quiz (PROJECT-SPEC Faza 4 comprehension check).
    /// </summary>
    public ListeningQuizResult GradeQuiz(IReadOnlyDictionary<Guid, int> answers)
    {
        if (_questions.Count == 0)
            throw new DomainException("This exercise has no comprehension questions.");

        var outcomes = new List<ListeningQuestionOutcome>(_questions.Count);
        foreach (var question in _questions)
        {
            var hasAnswer = answers.TryGetValue(question.Id, out var selected);
            if (!hasAnswer)
                selected = -1;

            outcomes.Add(new ListeningQuestionOutcome(
                question.Id,
                selected,
                question.CorrectOptionIndex,
                hasAnswer && question.IsCorrect(selected),
                question.HintCode,
                question.Explanation));
        }

        return new ListeningQuizResult(Id, _questions.Count, outcomes.Count(o => o.IsCorrect), outcomes);
    }
}
