import { uz } from "./uz";
import publicSeo from "./publicSeo.json";

const englishHome = publicSeo.find((route) => route.path === "/en/")!;

export const playLanding = {
  uz: {
    eyebrow: "INGLIZ TILI, O‘Z USULINGIZDA",
    headline: ["Bilish yaxshi.", "Gapirish zo‘r."],
    intro: ["Har kuni ozgina mashq.", "AI bilan haqiqiy suhbat."],
    start: "Bepul boshlash",
    noCard: "Karta kerak emas. Shunchaki boshlang.",
    comingSoon: "Tez kunda",
    download: "APK yuklab olish",
    android: "Android uchun",
    parrotAlt: "EnglishAI binafsha to‘tiqushi",
    reward: "Zo‘r! +10 XP",
    proof: ["A1 dan C2 gacha", "Sabrli AI suhbatdosh", "Kichik, aniq mashqlar"],
    discoverTitle: ["Bir mavzu.", "Olti xil kashfiyot."],
    discoverIntro: "Eshiting. Sinang. Ayting.",
    worldAlt: "Kitobdan ochilgan yangi dunyo",
    skills: ["Gapirib o‘rganing", "So‘zlar bilan tanishing", "Tinglab tushuning", "Qoidani sinab ko‘ring", "Yangi dunyoni o‘qing", "Fikringizni yozing"],
    demoEyebrow: "KELING, SINAB KO‘RAMIZ",
    demoTitle: ["Birinchi g‘alabangiz", "shu yerdan."],
    demoIntro: ["Xato qilish mumkin.", "Urinmaslik — zerikarli."],
    demoDay: "Bugun — 1-kun!",
    firstWord: "BIRINCHI SO‘Z",
    question: "Bu so‘z nimani anglatadi?",
    options: ["Salom", "Rahmat"],
    feedback: ["Javobni tanlab, birinchi qadamingizni qo‘ying.", "To‘ppa-to‘g‘ri! Shunday davom eting.", "Yana bir bor urinib ko‘ring. Hello — salom!"],
    stepsTitle: "Qiyin emas. Qiziq.",
    steps: ["Darajangizni toping", "Har kuni sinab ko‘ring", "Bemalol gapiring"],
    faqTitle: "Savolingiz bormi?",
    faqs: uz.marketing.faqs,
    finalEyebrow: "BIRINCHI QADAM BEPUL",
    finalTitle: ["Bugun bir so‘z.", "Ertaga bir suhbat."],
    finalNote: "Siz tayyorsiz. Biz ham.",
  },
  en: {
    eyebrow: "ENGLISH, YOUR OWN WAY",
    headline: ["Knowing is good.", "Speaking is better."],
    intro: ["A little practice every day.", "Real conversations with AI."],
    start: "Start for free",
    noCard: "No card needed. Just get started.",
    comingSoon: "Coming soon",
    download: "Download APK",
    android: "For Android",
    parrotAlt: "The purple EnglishAI parrot",
    reward: "Nice work! +10 XP",
    proof: ["From A1 to C2", "A patient AI speaking partner", "Small, focused exercises"],
    discoverTitle: ["One topic.", "Six ways to discover."],
    discoverIntro: "Listen. Try. Speak.",
    worldAlt: "A new world opening from a book",
    skills: ["Learn by speaking", "Discover new words", "Listen and understand", "Put the rules to work", "Read a new world", "Put ideas into words"],
    demoEyebrow: "LET’S GIVE IT A TRY",
    demoTitle: ["Your first small win", "starts right here."],
    demoIntro: ["Mistakes are welcome.", "Not trying? That’s boring."],
    demoDay: "Today is day one!",
    firstWord: "YOUR FIRST WORD",
    question: "When would you say this?",
    options: ["To greet someone", "To thank someone"],
    feedback: ["Choose an answer and take your first step.", "Exactly right! Keep it going.", "Try again. Hello is how you greet someone!"],
    stepsTitle: "Not difficult. Just fun.",
    steps: ["Find your level", "Try a little every day", "Speak with confidence"],
    faqTitle: "Have a question?",
    faqs: englishHome.faq.map(({ question, answer }) => ({ q: question, a: answer })),
    finalEyebrow: "YOUR FIRST STEP IS FREE",
    finalTitle: ["One word today.", "A conversation tomorrow."],
    finalNote: "You’re ready. So are we.",
  },
};

export const landingSkills = [
  { label: "Speaking", icon: "record_voice_over" },
  { label: "Vocabulary", icon: "style" },
  { label: "Listening", icon: "headphones" },
  { label: "Grammar", icon: "rule" },
  { label: "Reading", icon: "auto_stories" },
  { label: "Writing", icon: "edit" },
];
