import {
  Activity,
  AlarmClock,
  AlignLeft,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  AudioLines,
  AtSign,
  BadgeCheck,
  BarChart3,
  Bell,
  BellOff,
  BellPlus,
  BellRing,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Brain,
  Briefcase,
  Bug,
  Calculator,
  Camera,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CalendarX,
  Captions,
  CaptionsOff,
  ChartLine,
  ChartPie,
  Check,
  CheckCheck as Checks,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CirclePlay,
  CircleStop,
  CircleUserRound,
  CircleX,
  Compass,
  CircuitBoard,
  Clipboard,
  ClipboardCheck,
  Clock,
  CloudCheck,
  CloudOff,
  Code,
  Contrast,
  Coins,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Download,
  Drama,
  Dumbbell,
  Ear,
  EarOff,
  Ellipsis,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Frown,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Hand,
  Headphones,
  ImagePlus,
  Heart,
  HeartCrack,
  History,
  Hourglass,
  House,
  Hospital,
  IdCard,
  Info,
  KeyRound,
  Languages,
  LayoutGrid,
  LibraryBig,
  Lightbulb,
  Link,
  Link2Off,
  List,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Map,
  MapPin,
  Mars,
  Music,
  Maximize,
  Menu,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Mic,
  MicOff,
  Minimize,
  MonitorPlay,
  Moon,
  Network,
  Package,
  PanelLeft,
  Palette,
  PartyPopper,
  Pause,
  PawPrint,
  Pencil,
  PenTool,
  PiggyBank,
  PlaneTakeoff,
  Play,
  Utensils,
  Diamond,
  Plus,
  Puzzle,
  Quote,
  Radar,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  RotateCcw,
  RotateCw,
  Search,
  SearchX,
  ShoppingBag,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  Speech,
  SpellCheck,
  Square,
  SquarePen,
  Star,
  Sun,
  SunMoon,
  TreePine,
  Tag,
  Target,
  Timer,
  TimerOff,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Upload,
  User,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  Volume1,
  Volume2,
  VolumeX,
  Venus,
  WandSparkles,
  Wifi,
  WifiOff,
  Workflow,
  X,
  Apple,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Material-Symbol name → Lucide component. The app renders every icon through the
 * single <Icon name="..."> component (see Icon.tsx); this map is the one place the
 * old Material Symbols name strings are translated to Lucide icons, so migrating the
 * icon library never required touching the ~57 call sites.
 *
 * Names are the legacy Material Symbols identifiers still passed at call sites. When
 * adding a new icon, add its mapping here (any unmapped name renders the CircleHelp
 * fallback and logs a dev-only warning from Icon.tsx).
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  account_circle: CircleUserRound,
  add: Plus,
  adjust: CircleDot,
  admin_panel_settings: ShieldCheck,
  analytics: BarChart3,
  android: Smartphone,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  at: AtSign,
  auto_awesome: Sparkles,
  auto_edit: WandSparkles,
  auto_stories: BookOpen,
  badge: IdCard,
  bar_chart: BarChart3,
  bolt: Zap,
  book: BookOpen,
  cake: PartyPopper,
  bookmark_border: Bookmark,
  bookmark_add: BookMarked,
  bookmark_added: BookMarked,
  bookmarks: BookMarked,
  brightness_auto: SunMoon,
  bug_report: Bug,
  calculate: Calculator,
  calendar_month: Calendar,
  calendar_view_month: CalendarDays,
  calendar_view_week: CalendarDays,
  campaign: Megaphone,
  category: Tag,
  cancel: CircleX,
  celebration: PartyPopper,
  chat: MessageCircle,
  checklist: ListChecks,
  chat_bubble: MessageSquare,
  support_agent: Headphones,
  add_photo_alternate: ImagePlus,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ArrowLeft,
  chevron_down: ChevronDown,
  chevron_right: ChevronRight,
  close: X,
  cloud_done: CloudCheck,
  cloud_off: CloudOff,
  content_copy: Copy,
  content_paste: Clipboard,
  contrast: Contrast,
  conversion_path: Workflow,
  dark_mode: Moon,
  dashboard: LayoutGrid,
  database: Database,
  date_range: CalendarRange,
  delete: Trash2,
  delete_forever: Trash2,
  delete_sweep: Trash2,
  developer_board: CircuitBoard,
  developer_mode: Code,
  devices: Smartphone,
  diversity_3: Users,
  dns: Server,
  done: Check,
  done_all: Checks,
  donut_small: ChartPie,
  download: Download,
  edit: Pencil,
  edit_note: SquarePen,
  emoji_events: Trophy,
  error: CircleAlert,
  error_outline: CircleAlert,
  event: Calendar,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  event_repeat: CalendarClock,
  expand: Expand,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  extension: Puzzle,
  face: Smile,
  fact_check: ClipboardCheck,
  fitness_center: Dumbbell,
  flag: Flag,
  flight_takeoff: PlaneTakeoff,
  folder: Folder,
  format_list_numbered: ListOrdered,
  format_quote: Quote,
  forum: MessagesSquare,
  fullscreen: Maximize,
  fullscreen_exit: Minimize,
  fullscreen_open: Maximize,
  graphic_eq: AudioLines,
  grid_view: LayoutGrid,
  group: Users,
  group_add: UserPlus,
  groups: Users,
  palette: Palette,
  pin: MapPin,
  restaurant: Utensils,
  diamond: Diamond,
  headphones: Headphones,
  heart: Heart,
  heart_broken: HeartCrack,
  hearing: Ear,
  hearing_disabled: EarOff,
  help: CircleHelp,
  flame: Flame,
  "badge-check": BadgeCheck,
  compass: Compass,
  menu: Menu,
  history: History,
  home: House,
  health_and_safety: Hospital,
  hourglass_bottom: Hourglass,
  hourglass_empty: Hourglass,
  hourglass_top: Hourglass,
  hub: Network,
  info: Info,
  inbox: Package,
  input: LogIn,
  insights: ChartLine,
  inventory_2: Package,
  key: KeyRound,
  lan: Network,
  leaderboard: BarChart3,
  library_books: LibraryBig,
  library_music: AudioLines,
  light_mode: Sun,
  lightbulb: Lightbulb,
  link: Link,
  link_off: Link2Off,
  list: List,
  local_fire_department: Flame,
  lock: Lock,
  lock_open: LockOpen,
  mars: Mars,
  login: LogIn,
  logout: LogOut,
  lyrics: Captions,
  manage_accounts: UserCog,
  map: Map,
  location_on: MapPin,
  music_note: Music,
  mail: AtSign,
  memory: Cpu,
  menu_book: BookOpen,
  mic: Mic,
  mic_off: MicOff,
  military_tech: Medal,
  monitor_heart: Activity,
  monitoring: Activity,
  more_horiz: Ellipsis,
  near_me: Send,
  notes: AlignLeft,
  notification_add: BellPlus,
  notifications: Bell,
  notifications_active: BellRing,
  notifications_off: BellOff,
  open_in_full: Expand,
  open_in_new: ExternalLink,
  pause: Pause,
  panel_left: PanelLeft,
  paid: Coins,
  payments: CreditCard,
  pending: Ellipsis,
  person: User,
  person_add: UserPlus,
  person_remove: UserMinus,
  pets: PawPrint,
  photo_camera: Camera,
  play_arrow: Play,
  play_circle: CirclePlay,
  priority_high: CircleAlert,
  progress_activity: LoaderCircle,
  psychology: Brain,
  quiz: ListChecks,
  radar: Radar,
  rate_review: MessageSquareText,
  record_voice_over: Speech,
  recording: Circle,
  radio_button_unchecked: Circle,
  recycling: Recycle,
  redeem: Gift,
  refresh: RefreshCw,
  repeat: Repeat,
  replay: RotateCcw,
  replay_5: RotateCcw,
  forward_5: RotateCw,
  restart_alt: RotateCcw,
  rocket_launch: Rocket,
  route: Route,
  routine: Repeat,
  rule: SpellCheck,
  savings: PiggyBank,
  schedule: Clock,
  schedule_send: AlarmClock,
  save: Download,
  school: GraduationCap,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  shopping_bag: ShoppingBag,
  self_improvement: Sparkles,
  sell: Tag,
  send: Send,
  target: Target,
  sentiment_dissatisfied: Frown,
  sentiment_satisfied: Smile,
  settings: Settings,
  shield: Shield,
  shield_person: ShieldCheck,
  signal_cellular_alt: BarChart3,
  show_chart: ChartLine,
  slow_motion_video: Gauge,
  smart_display: MonitorPlay,
  smart_toy: Bot,
  sparkles: Sparkles,
  speed: Gauge,
  spellcheck: SpellCheck,
  star: Star,
  stars: Sparkles,
  stop: Square,
  stop_circle: CircleStop,
  style: Palette,
  subject: AlignLeft,
  storage: Database,
  subtitles: Captions,
  subtitles_off: CaptionsOff,
  swap_horiz: ArrowRightLeft,
  swipe: ArrowRightLeft,
  task_alt: CircleCheck,
  theater_comedy: Drama,
  timer: Timer,
  timer_off: TimerOff,
  tips_and_updates: Lightbulb,
  today: CalendarDays,
  nature: TreePine,
  title: AlignLeft,
  translate: Languages,
  travel_explore: Globe,
  trending_up: TrendingUp,
  trophy: Trophy,
  tune: SlidersHorizontal,
  upload_file: Upload,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  venus: Venus,
  visibility: Eye,
  visibility_off: EyeOff,
  volume_up: Volume2,
  volume_down: Volume1,
  volume_off: VolumeX,
  warning: TriangleAlert,
  waving_hand: Hand,
  widgets: LayoutGrid,
  view_module: LayoutGrid,
  wifi: Wifi,
  wifi_off: WifiOff,
  work: Briefcase,
  workspace_premium: Crown,
  smartphone: Smartphone,
  apple: Apple,
  draw: PenTool,
  favorite: Heart,
  flip: RotateCcw,
};
