// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnglishAiDbContext))]
    [Migration("20260623053200_AddTopicSpeakingProgress")]
    partial class AddTopicSpeakingProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Grammar.GrammarLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ContextIntro")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExplanationCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Level");

                    b.ToTable("GrammarLessons", (string)null);
                });

            modelBuilder.Entity("Domain.Learning.LearnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmationTestPassedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastWinBackStage")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("LearnerProfiles", (string)null);
                });

            modelBuilder.Entity("Domain.Reading.ReadingPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.ToTable("ReadingPassages", (string)null);
                });

            modelBuilder.Entity("Domain.Retention.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags", (string)null);
                });

            modelBuilder.Entity("Domain.Subscription.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AmountUzs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Domain.Subscription.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Domain.Video.VideoLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.ToTable("VideoLessons", (string)null);
                });

            modelBuilder.Entity("Domain.Vocabulary.TopicSpeakingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LearnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<double>("SpokenSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VocabularyTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId", "LearnedAt");

                    b.HasIndex("LearnerId", "VocabularyTopicId")
                        .IsUnique();

                    b.ToTable("TopicSpeakingProgress", (string)null);
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("VocabularyItems", (string)null);
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Passage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleUz")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("VocabularyTopics", (string)null);
                });

            modelBuilder.Entity("Domain.Writing.WritingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWords")
                        .HasColumnType("integer");

                    b.Property<int>("MinWords")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.ToTable("WritingTasks", (string)null);
                });

            modelBuilder.Entity("Domain.Grammar.GrammarLesson", b =>
                {
                    b.OwnsMany("Domain.Grammar.GrammarApplicationTask", "ApplicationTasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("GrammarLessonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("TargetSkill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("GrammarLessonId");

                            b1.ToTable("GrammarApplicationTasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GrammarLessonId");
                        });

                    b.OwnsMany("Domain.Grammar.GrammarExercise", "Exercises", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<Guid>("GrammarLessonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("GrammarLessonId");

                            b1.ToTable("GrammarExercises", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GrammarLessonId");
                        });

                    b.Navigation("ApplicationTasks");

                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Domain.Learning.LearnerProfile", b =>
                {
                    b.OwnsMany("Domain.Learning.ErrorObservation", "Errors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Category")
                                .HasColumnType("integer");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.HasIndex("OccurredAt");

                            b1.ToTable("LearnerErrorObservations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.OwnsMany("Domain.Learning.SkillActivity", "Activities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.HasIndex("OccurredAt");

                            b1.ToTable("LearnerSkillActivities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.OwnsMany("Domain.Learning.SkillSeed", "Seeds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Score")
                                .HasColumnType("double precision");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.ToTable("LearnerSkillSeeds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.Navigation("Activities");

                    b.Navigation("Errors");

                    b.Navigation("Seeds");
                });

            modelBuilder.Entity("Domain.Reading.ReadingPassage", b =>
                {
                    b.OwnsMany("Domain.Reading.GlossaryEntry", "Glossary", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExampleSentence")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("ReadingPassageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Translation")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Word")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("Id");

                            b1.HasIndex("ReadingPassageId");

                            b1.ToTable("ReadingGlossaryEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReadingPassageId");
                        });

                    b.OwnsMany("Domain.Reading.ReadingQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("ReadingPassageId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ReadingPassageId");

                            b1.ToTable("ReadingComprehensionQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReadingPassageId");
                        });

                    b.Navigation("Glossary");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Retention.FeatureFlag", b =>
                {
                    b.OwnsMany("Domain.Retention.FeatureVariant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("FeatureFlagId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("FeatureFlagId");

                            b1.ToTable("FeatureVariants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FeatureFlagId");
                        });

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Domain.Video.VideoLesson", b =>
                {
                    b.OwnsMany("Domain.Video.ComprehensionQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("VideoLessonId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VideoLessonId");

                            b1.ToTable("VideoComprehensionQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VideoLessonId");
                        });

                    b.OwnsMany("Domain.Video.TranscriptSegment", "Transcript", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<double>("EndSeconds")
                                .HasColumnType("double precision");

                            b1.Property<string>("EnglishText")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<double>("StartSeconds")
                                .HasColumnType("double precision");

                            b1.Property<string>("UzbekTranslation")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("VideoLessonId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VideoLessonId");

                            b1.ToTable("VideoTranscriptSegments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VideoLessonId");

                            b1.OwnsMany("Domain.Video.TranscriptWord", "Words", b2 =>
                                {
                                    b2.Property<Guid>("TranscriptSegmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<double>("EndSeconds")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("StartSeconds")
                                        .HasColumnType("double precision");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(60)
                                        .HasColumnType("character varying(60)");

                                    b2.HasKey("TranscriptSegmentId", "Id");

                                    b2.ToTable("VideoTranscriptWords", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TranscriptSegmentId");
                                });

                            b1.Navigation("Words");
                        });

                    b.OwnsMany("Domain.Video.VideoGlossaryEntry", "Glossary", b1 =>
                        {
                            b1.Property<Guid>("VideoLessonId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("UzbekMeaning")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<string>("Word")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.HasKey("VideoLessonId", "Id");

                            b1.ToTable("VideoLessons");

                            b1.ToJson("Glossary");

                            b1.WithOwner()
                                .HasForeignKey("VideoLessonId");
                        });

                    b.Navigation("Glossary");

                    b.Navigation("Questions");

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyItem", b =>
                {
                    b.OwnsOne("Domain.Vocabulary.ReviewSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("VocabularyItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FailCount")
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("LearnedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("NextReviewAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Stage")
                                .HasColumnType("integer");

                            b1.HasKey("VocabularyItemId");

                            b1.HasIndex("NextReviewAt");

                            b1.ToTable("VocabularyItems");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyItemId");
                        });

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyTopic", b =>
                {
                    b.OwnsMany("Domain.Vocabulary.TopicWord", "Words", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ExampleSentence")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Translation")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("VocabularyTopicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Word")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("VocabularyTopicId");

                            b1.ToTable("VocabularyTopicWords", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VocabularyTopicId");
                        });

                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
