// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnglishAiDbContext))]
    [Migration("20260621235753_AddReadingPassages")]
    partial class AddReadingPassages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Learning.LearnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmationTestPassedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("LearnerProfiles", (string)null);
                });

            modelBuilder.Entity("Domain.Reading.ReadingPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.ToTable("ReadingPassages", (string)null);
                });

            modelBuilder.Entity("Domain.Subscription.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AmountUzs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Domain.Subscription.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Domain.Video.VideoLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.ToTable("VideoLessons", (string)null);
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("VocabularyItems", (string)null);
                });

            modelBuilder.Entity("Domain.Learning.LearnerProfile", b =>
                {
                    b.OwnsMany("Domain.Learning.ErrorObservation", "Errors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Category")
                                .HasColumnType("integer");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.HasIndex("OccurredAt");

                            b1.ToTable("LearnerErrorObservations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.OwnsMany("Domain.Learning.SkillActivity", "Activities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.HasIndex("OccurredAt");

                            b1.ToTable("LearnerSkillActivities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.OwnsMany("Domain.Learning.SkillSeed", "Seeds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Score")
                                .HasColumnType("double precision");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.ToTable("LearnerSkillSeeds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.Navigation("Activities");

                    b.Navigation("Errors");

                    b.Navigation("Seeds");
                });

            modelBuilder.Entity("Domain.Reading.ReadingPassage", b =>
                {
                    b.OwnsMany("Domain.Reading.GlossaryEntry", "Glossary", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExampleSentence")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("ReadingPassageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Translation")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Word")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("Id");

                            b1.HasIndex("ReadingPassageId");

                            b1.ToTable("ReadingGlossaryEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReadingPassageId");
                        });

                    b.OwnsMany("Domain.Reading.ReadingQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("ReadingPassageId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ReadingPassageId");

                            b1.ToTable("ReadingComprehensionQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReadingPassageId");
                        });

                    b.Navigation("Glossary");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Video.VideoLesson", b =>
                {
                    b.OwnsMany("Domain.Video.ComprehensionQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("VideoLessonId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VideoLessonId");

                            b1.ToTable("VideoComprehensionQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VideoLessonId");
                        });

                    b.OwnsMany("Domain.Video.TranscriptSegment", "Transcript", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<double>("EndSeconds")
                                .HasColumnType("double precision");

                            b1.Property<string>("EnglishText")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<double>("StartSeconds")
                                .HasColumnType("double precision");

                            b1.Property<string>("UzbekTranslation")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("VideoLessonId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VideoLessonId");

                            b1.ToTable("VideoTranscriptSegments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VideoLessonId");
                        });

                    b.Navigation("Questions");

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyItem", b =>
                {
                    b.OwnsOne("Domain.Vocabulary.ReviewSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("VocabularyItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FailCount")
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("LearnedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("NextReviewAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Stage")
                                .HasColumnType("integer");

                            b1.HasKey("VocabularyItemId");

                            b1.HasIndex("NextReviewAt");

                            b1.ToTable("VocabularyItems");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyItemId");
                        });

                    b.Navigation("Schedule")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
