// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnglishAiDbContext))]
    [Migration("20260729220002_AddUniqueTopicVocabularyItemsV2")]
    partial class AddUniqueTopicVocabularyItemsV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Analytics.DailyStudyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("GrammarSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ListeningSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("ReadingSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("SpeakingSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("VocabularySeconds")
                        .HasColumnType("integer");

                    b.Property<int>("WritingSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId", "Day")
                        .IsUnique();

                    b.ToTable("DailyStudyRecords", (string)null);
                });

            modelBuilder.Entity("Domain.Analytics.ProductEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("LearnerId", "Type");

                    b.HasIndex("LearnerId", "Type", "Source");

                    b.ToTable("ProductEvents", (string)null);
                });

            modelBuilder.Entity("Domain.Assistant.AssistantMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.HasIndex("SessionId", "ClientRequestId", "Role")
                        .IsUnique()
                        .HasFilter("\"ClientRequestId\" IS NOT NULL");

                    b.ToTable("AssistantMessages", (string)null);
                });

            modelBuilder.Entity("Domain.Assistant.AssistantSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId", "ExpiresAt");

                    b.HasIndex("LearnerId", "Skill", "ResourceType", "ResourceId", "UpdatedAt");

                    b.ToTable("AssistantSessions", (string)null);
                });

            modelBuilder.Entity("Domain.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("CoverAttribution")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CoverImageQuery")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleUz")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("Domain.Books.BookProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("LearnerId", "BookId")
                        .IsUnique();

                    b.ToTable("BookProgress", (string)null);
                });

            modelBuilder.Entity("Domain.Competition.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AccessCodeSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentSlideIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1);

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostLearnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TopicIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Competitions", (string)null);
                });

            modelBuilder.Entity("Domain.Developer.DeveloperApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Prefix", "RevokedAt");

                    b.ToTable("DeveloperApiKeys", (string)null);
                });

            modelBuilder.Entity("Domain.Gamification.DiscountRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("CoinsSpent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LearnerId");

                    b.ToTable("DiscountRedemptions", (string)null);
                });

            modelBuilder.Entity("Domain.Gamification.LearnerPoints", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Energy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<DateTimeOffset>("EnergyRefilledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("date_trunc('hour', now() at time zone 'utc') at time zone 'utc'");

                    b.Property<int>("HighestStreakMilestoneReached")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("LifetimeXp")
                        .HasColumnType("bigint");

                    b.Property<long>("SpendableCoins")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("LearnerPoints", (string)null);
                });

            modelBuilder.Entity("Domain.Grammar.GrammarCommonMistake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GrammarLessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrammarLessonId");

                    b.ToTable("GrammarCommonMistake");
                });

            modelBuilder.Entity("Domain.Grammar.GrammarExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GrammarLessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Uzbek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrammarLessonId");

                    b.ToTable("GrammarExample");
                });

            modelBuilder.Entity("Domain.Grammar.GrammarLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ContextIntro")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CuratedFormulas")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CuratedSummaryUz")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("CuratedTitleUz")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExplanationCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("GrammarFocusCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("VocabularyTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Level");

                    b.HasIndex("VocabularyTopicId");

                    b.ToTable("GrammarLessons", (string)null);
                });

            modelBuilder.Entity("Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("ProTrialExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("Domain.Identity.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DailyGoal")
                        .HasColumnType("integer");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageBalance")
                        .HasColumnType("integer");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("Domain.Learning.LearnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmationTestPassedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastWinBackStage")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("LearningGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("OverallLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("LearnerProfiles", (string)null);
                });

            modelBuilder.Entity("Domain.Listening.ListeningExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("VocabularyTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("VocabularyTopicId");

                    b.ToTable("ListeningExercises", (string)null);
                });

            modelBuilder.Entity("Domain.Notifications.AdminBroadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AdminBroadcasts", (string)null);
                });

            modelBuilder.Entity("Domain.Notifications.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("DeviceTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Notifications.NotificationArrival", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("NotificationArrivals", (string)null);
                });

            modelBuilder.Entity("Domain.Notifications.NotificationDismissal", b =>
                {
                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LearnerId", "NotificationId");

                    b.ToTable("NotificationDismissals", (string)null);
                });

            modelBuilder.Entity("Domain.Notifications.NotificationReadState", b =>
                {
                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LearnerId");

                    b.ToTable("NotificationReadStates", (string)null);
                });

            modelBuilder.Entity("Domain.Reading.ReadingPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ContextGaps")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("VocabularyTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("VocabularyTopicId");

                    b.ToTable("ReadingPassages", (string)null);
                });

            modelBuilder.Entity("Domain.Referral.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("QualifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RefereeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferrerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId")
                        .IsUnique();

                    b.HasIndex("ReferrerId");

                    b.ToTable("Referrals", (string)null);
                });

            modelBuilder.Entity("Domain.Referral.ReferralAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BonusTopicAllowance")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("RemainingSpeakingCredits")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingWritingCredits")
                        .HasColumnType("integer");

                    b.Property<int>("RewardedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("ReferralAccounts", (string)null);
                });

            modelBuilder.Entity("Domain.Retention.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags", (string)null);
                });

            modelBuilder.Entity("Domain.Subscription.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AmountUzs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Domain.Subscription.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Domain.Video.VideoLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("TranscriptStatus")
                        .HasColumnType("integer");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("YouTubeVideoId")
                        .IsUnique();

                    b.HasIndex("Status", "Level", "CreatedAt");

                    b.ToTable("VideoLessons", (string)null);
                });

            modelBuilder.Entity("Domain.Vocabulary.TopicCompletionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset?>("MasteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VocabularyTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId", "MasteredAt");

                    b.HasIndex("LearnerId", "VocabularyTopicId")
                        .IsUnique();

                    b.ToTable("TopicCompletionRecords", (string)null);
                });

            modelBuilder.Entity("Domain.Vocabulary.TopicSpeakingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LearnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<double>("SpokenSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VocabularyTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId", "LearnedAt");

                    b.HasIndex("LearnerId", "VocabularyTopicId")
                        .IsUnique();

                    b.ToTable("TopicSpeakingProgress", (string)null);
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PartOfSpeech")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId", "CreatedAt");

                    b.HasIndex("LearnerId", "SourceTopicId", "Word")
                        .IsUnique()
                        .HasFilter("\"SourceTopicId\" IS NOT NULL");

                    b.ToTable("VocabularyItems", (string)null);
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("ContentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrammarFocusCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasDefaultValue("");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Passage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleUz")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Level", "Sequence");

                    b.ToTable("VocabularyTopics", (string)null);
                });

            modelBuilder.Entity("Domain.Writing.WritingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Guidance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWords")
                        .HasColumnType("integer");

                    b.Property<int>("MinWords")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VocabularyTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("VocabularyTopicId");

                    b.ToTable("WritingTasks", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Identity.Avatar.UserAvatar", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserAvatars", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Images.TopicImage", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<string>("Attribution")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("TopicId", "Slot");

                    b.ToTable("TopicImages", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Listening.ListeningAudioClip", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AudioContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExerciseId");

                    b.ToTable("ListeningAudioClips", (string)null);
                });

            modelBuilder.Entity("Domain.Assistant.AssistantMessage", b =>
                {
                    b.HasOne("Domain.Assistant.AssistantSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Books.Book", b =>
                {
                    b.OwnsMany("Domain.Books.BookSection", "Sections", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)");

                            b1.Property<Guid>("BookId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("BookId", "Order");

                            b1.ToTable("BookSections", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookId");

                            b1.OwnsMany("Domain.Books.BookQuestion", "Questions", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("BookSectionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("CorrectOptionIndex")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Explanation")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.Property<string>("Options")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Prompt")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("BookSectionId");

                                    b2.ToTable("BookComprehensionQuestions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("BookSectionId");
                                });

                            b1.Navigation("Questions");
                        });

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Domain.Books.BookProgress", b =>
                {
                    b.OwnsMany("Domain.Books.BookSectionScore", "Sections", b1 =>
                        {
                            b1.Property<Guid>("BookProgressId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SectionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AchievedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("BestCorrectCount")
                                .HasColumnType("integer");

                            b1.Property<bool>("Passed")
                                .HasColumnType("boolean");

                            b1.HasKey("BookProgressId", "SectionId");

                            b1.ToTable("BookSectionScores", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookProgressId");
                        });

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Domain.Competition.Competition", b =>
                {
                    b.OwnsOne("Domain.Competition.CompetitionSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("CompetitionId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowLateJoin")
                                .HasColumnType("boolean")
                                .HasColumnName("Settings_AllowLateJoin");

                            b1.Property<bool>("AutoAdvance")
                                .HasColumnType("boolean")
                                .HasColumnName("Settings_AutoAdvance");

                            b1.Property<int>("BasePointsPerCorrect")
                                .HasColumnType("integer")
                                .HasColumnName("Settings_BasePointsPerCorrect");

                            b1.Property<int>("QuestionsPerTopic")
                                .HasColumnType("integer")
                                .HasColumnName("Settings_QuestionsPerTopic");

                            b1.Property<bool>("ShowLiveLeaderboard")
                                .HasColumnType("boolean")
                                .HasColumnName("Settings_ShowLiveLeaderboard");

                            b1.Property<bool>("ShuffleSlides")
                                .HasColumnType("boolean")
                                .HasColumnName("Settings_ShuffleSlides");

                            b1.Property<int>("SlideDurationSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("Settings_SlideDurationSeconds");

                            b1.HasKey("CompetitionId");

                            b1.ToTable("Competitions");

                            b1.WithOwner()
                                .HasForeignKey("CompetitionId");
                        });

                    b.OwnsMany("Domain.Competition.CompetitionSlide", "Slides", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<Guid>("CompetitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.Property<string>("QuestionText")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("SourceTopicId")
                                .HasColumnType("uuid");

                            b1.Property<int>("SourceType")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("CompetitionId");

                            b1.ToTable("CompetitionSlides", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompetitionId");
                        });

                    b.OwnsMany("Domain.Competition.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<Guid>("CompetitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<bool>("IsHost")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false);

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("LearnerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Score")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.Property<int>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.HasKey("Id");

                            b1.HasIndex("CompetitionId");

                            b1.ToTable("CompetitionParticipants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompetitionId");

                            b1.OwnsMany("Domain.Competition.SlideAnswer", "Answers", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset>("AnsweredAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<bool>("IsCorrect")
                                        .HasColumnType("boolean");

                                    b2.Property<Guid>("ParticipantId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("PointsAwarded")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SelectedOptionIndex")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("SlideId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ParticipantId");

                                    b2.ToTable("CompetitionAnswers", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ParticipantId");
                                });

                            b1.Navigation("Answers");
                        });

                    b.Navigation("Participants");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Slides");
                });

            modelBuilder.Entity("Domain.Developer.DeveloperApiKey", b =>
                {
                    b.HasOne("Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Grammar.GrammarCommonMistake", b =>
                {
                    b.HasOne("Domain.Grammar.GrammarLesson", null)
                        .WithMany("CommonMistakes")
                        .HasForeignKey("GrammarLessonId");
                });

            modelBuilder.Entity("Domain.Grammar.GrammarExample", b =>
                {
                    b.HasOne("Domain.Grammar.GrammarLesson", null)
                        .WithMany("Examples")
                        .HasForeignKey("GrammarLessonId");
                });

            modelBuilder.Entity("Domain.Grammar.GrammarLesson", b =>
                {
                    b.OwnsMany("Domain.Grammar.GrammarApplicationTask", "ApplicationTasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("GrammarLessonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<int>("TargetSkill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("GrammarLessonId");

                            b1.ToTable("GrammarApplicationTasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GrammarLessonId");
                        });

                    b.OwnsMany("Domain.Grammar.GrammarCuratedRule", "CuratedRules", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("BodyUz")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<Guid>("GrammarLessonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HeadingUz")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.HasKey("Id");

                            b1.HasIndex("GrammarLessonId");

                            b1.ToTable("GrammarCuratedRules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GrammarLessonId");
                        });

                    b.OwnsMany("Domain.Grammar.GrammarExercise", "Exercises", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("Explanation")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("GrammarLessonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("GrammarLessonId");

                            b1.ToTable("GrammarExercises", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GrammarLessonId");
                        });

                    b.Navigation("ApplicationTasks");

                    b.Navigation("CuratedRules");

                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Domain.Learning.LearnerProfile", b =>
                {
                    b.OwnsMany("Domain.Learning.ErrorObservation", "Errors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Category")
                                .HasColumnType("integer");

                            b1.Property<string>("ExpectedAnswer")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Explanation")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("LearnerAnswer")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Prompt")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.Property<string>("Source")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<Guid?>("SourceId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.HasIndex("OccurredAt");

                            b1.HasIndex("Source", "SourceId");

                            b1.ToTable("LearnerErrorObservations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.OwnsMany("Domain.Learning.SkillActivity", "Activities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.HasIndex("OccurredAt");

                            b1.ToTable("LearnerSkillActivities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.OwnsMany("Domain.Learning.SkillSeed", "Seeds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Score")
                                .HasColumnType("double precision");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.ToTable("LearnerSkillSeeds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.Navigation("Activities");

                    b.Navigation("Errors");

                    b.Navigation("Seeds");
                });

            modelBuilder.Entity("Domain.Listening.ListeningExercise", b =>
                {
                    b.OwnsMany("Domain.Listening.ListeningQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("Explanation")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<Guid>("ListeningExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.HasKey("Id");

                            b1.HasIndex("ListeningExerciseId");

                            b1.ToTable("ListeningComprehensionQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ListeningExerciseId");
                        });

                    b.OwnsMany("Domain.Listening.ListeningSegment", "Segments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("EndMs")
                                .HasColumnType("integer");

                            b1.Property<Guid>("ListeningExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Speaker")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("StartMs")
                                .HasColumnType("integer");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.HasKey("Id");

                            b1.HasIndex("ListeningExerciseId", "Order");

                            b1.ToTable("ListeningSegments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ListeningExerciseId");
                        });

                    b.Navigation("Questions");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("Domain.Reading.ReadingPassage", b =>
                {
                    b.OwnsMany("Domain.Reading.GlossaryEntry", "Glossary", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExampleSentence")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("ReadingPassageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Translation")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Word")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("Id");

                            b1.HasIndex("ReadingPassageId");

                            b1.ToTable("ReadingGlossaryEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReadingPassageId");
                        });

                    b.OwnsMany("Domain.Reading.ReadingQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("Explanation")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("ReadingPassageId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ReadingPassageId");

                            b1.ToTable("ReadingComprehensionQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReadingPassageId");
                        });

                    b.Navigation("Glossary");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Retention.FeatureFlag", b =>
                {
                    b.OwnsMany("Domain.Retention.FeatureVariant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("FeatureFlagId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("FeatureFlagId");

                            b1.ToTable("FeatureVariants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FeatureFlagId");
                        });

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Domain.Video.VideoLesson", b =>
                {
                    b.OwnsMany("Domain.Video.ComprehensionQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CorrectOptionIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("HintCode")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("VideoLessonId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VideoLessonId");

                            b1.ToTable("VideoComprehensionQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VideoLessonId");
                        });

                    b.OwnsMany("Domain.Video.TranscriptSegment", "Transcript", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<double>("EndSeconds")
                                .HasColumnType("double precision");

                            b1.Property<string>("EnglishText")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<double>("StartSeconds")
                                .HasColumnType("double precision");

                            b1.Property<string>("UzbekTranslation")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("VideoLessonId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VideoLessonId");

                            b1.ToTable("VideoTranscriptSegments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VideoLessonId");

                            b1.OwnsMany("Domain.Video.TranscriptWord", "Words", b2 =>
                                {
                                    b2.Property<Guid>("TranscriptSegmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<double>("EndSeconds")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("StartSeconds")
                                        .HasColumnType("double precision");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(60)
                                        .HasColumnType("character varying(60)");

                                    b2.HasKey("TranscriptSegmentId", "Id");

                                    b2.ToTable("VideoTranscriptWords", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TranscriptSegmentId");
                                });

                            b1.Navigation("Words");
                        });

                    b.OwnsMany("Domain.Video.VideoGlossaryEntry", "Glossary", b1 =>
                        {
                            b1.Property<Guid>("VideoLessonId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("UzbekMeaning")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<string>("Word")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.HasKey("VideoLessonId", "Id");

                            b1.ToTable("VideoLessons");

                            b1.ToJson("Glossary");

                            b1.WithOwner()
                                .HasForeignKey("VideoLessonId");
                        });

                    b.Navigation("Glossary");

                    b.Navigation("Questions");

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("Domain.Vocabulary.TopicCompletionRecord", b =>
                {
                    b.OwnsMany("Domain.Vocabulary.TopicModuleScore", "ModuleScores", b1 =>
                        {
                            b1.Property<Guid>("TopicCompletionRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Module")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<DateTimeOffset>("AchievedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("TopicCompletionRecordId", "Module");

                            b1.ToTable("TopicModuleScores", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TopicCompletionRecordId");
                        });

                    b.Navigation("ModuleScores");
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyItem", b =>
                {
                    b.OwnsOne("Domain.Vocabulary.ReviewSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("VocabularyItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FailCount")
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("LastHintCount")
                                .HasColumnType("integer");

                            b1.Property<int?>("LastResponseLatencyMs")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("LearnedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("NextReviewAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("ReviewCount")
                                .HasColumnType("integer");

                            b1.Property<int>("Stage")
                                .HasColumnType("integer");

                            b1.HasKey("VocabularyItemId");

                            b1.HasIndex("NextReviewAt");

                            b1.ToTable("VocabularyItems");

                            b1.WithOwner()
                                .HasForeignKey("VocabularyItemId");
                        });

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Vocabulary.VocabularyTopic", b =>
                {
                    b.OwnsMany("Domain.Vocabulary.TopicWord", "Words", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ExampleSentence")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("ImageAttribution")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("ImageSource")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(800)
                                .HasColumnType("character varying(800)");

                            b1.Property<int>("PartOfSpeech")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.Property<string>("Translation")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("VocabularyTopicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Word")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("VocabularyTopicId");

                            b1.ToTable("VocabularyTopicWords", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VocabularyTopicId");
                        });

                    b.Navigation("Words");
                });

            modelBuilder.Entity("Domain.Assistant.AssistantSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Grammar.GrammarLesson", b =>
                {
                    b.Navigation("CommonMistakes");

                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
