// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnglishAiDbContext))]
    [Migration("20260621202758_AddLearnerProfile")]
    partial class AddLearnerProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Learning.LearnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmationTestPassedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("LearnerProfiles", (string)null);
                });

            modelBuilder.Entity("Domain.Learning.LearnerProfile", b =>
                {
                    b.OwnsMany("Domain.Learning.ErrorObservation", "Errors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Category")
                                .HasColumnType("integer");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.HasIndex("OccurredAt");

                            b1.ToTable("LearnerErrorObservations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.OwnsMany("Domain.Learning.SkillActivity", "Activities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.HasIndex("OccurredAt");

                            b1.ToTable("LearnerSkillActivities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.OwnsMany("Domain.Learning.SkillSeed", "Seeds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LearnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Score")
                                .HasColumnType("double precision");

                            b1.Property<int>("Skill")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerProfileId");

                            b1.ToTable("LearnerSkillSeeds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearnerProfileId");
                        });

                    b.Navigation("Activities");

                    b.Navigation("Errors");

                    b.Navigation("Seeds");
                });
#pragma warning restore 612, 618
        }
    }
}
