namespace Application.Speaking.Ports;

/// <summary>
/// Resolves a content code to a verified Uzbek template string (docs/development-guide.md rule 11:
/// Uzbek text is never free-generated by the LLM - only filled-in templates).
/// Placeholders like <c>{word}</c> are replaced from <paramref name="args"/>.
/// </summary>
public interface IFeedbackTemplateProvider
{
    /// <summary>Returns the filled template, or <c>null</c> if the code is unknown.</summary>
    string? Get(string code, IReadOnlyDictionary<string, string>? args = null);
}
