using Domain.Common;

namespace Domain.Books;

/// <summary>
/// One chapter/section of a <see cref="Book"/>. Seeded as a pending shell (order + title only);
/// its English body and exactly <see cref="QuestionsPerSection"/> comprehension questions are
/// generated by the LLM on first open and cached via <see cref="FillContent"/> (the same
/// lazy-fill pattern as a reading lesson, docs/development-guide.md rules 8, 10). A learner finishes a section
/// by passing its quiz; finishing every section marks the book read.
/// </summary>
public sealed class BookSection
{
    /// <summary>Number of comprehension questions every filled section carries (product rule).</summary>
    public const int QuestionsPerSection = 10;

    private readonly List<BookQuestion> _questions = new();

    // Parameterless ctor for EF Core materialization.
    private BookSection()
    {
        Title = null!;
        Body = null!;
    }

    private BookSection(int order, string title)
    {
        Id = Guid.NewGuid();
        Order = order;
        Title = title;
        Body = string.Empty;
        Status = BookSectionStatus.Pending;
    }

    public Guid Id { get; private set; }

    /// <summary>1-based reading order of the section within the book.</summary>
    public int Order { get; private set; }

    /// <summary>The section title shown in the book's table of contents and the reader.</summary>
    public string Title { get; private set; }

    /// <summary>The full English text of the section; empty until the section is filled.</summary>
    public string Body { get; private set; }

    /// <summary>Pending until the body and ten questions are generated and cached.</summary>
    public BookSectionStatus Status { get; private set; }

    public IReadOnlyList<BookQuestion> Questions => _questions;

    /// <summary>True once the section text and questions have been generated and cached.</summary>
    public bool IsFilled => Status == BookSectionStatus.Filled;

    /// <summary>Number of words in the section body (reader/length indicator).</summary>
    public int WordCount => string.IsNullOrEmpty(Body)
        ? 0
        : Body.Split(new[] { ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries).Length;

    /// <summary>Creates a pending section shell (used by the seeded catalog outline).</summary>
    public static BookSection Pending(int order, string title)
    {
        if (order < 1)
            throw new DomainException("Section order must be 1-based and positive.");
        if (string.IsNullOrWhiteSpace(title))
            throw new DomainException("Section title must not be empty.");

        return new BookSection(order, title.Trim());
    }

    /// <summary>
    /// Stores the generated body and exactly <see cref="QuestionsPerSection"/> comprehension
    /// questions, marking the section filled. Called once after the LLM produces the content;
    /// later reads serve the cache. Requiring exactly ten questions keeps section quizzes consistent
    /// meaningful - a partial generation leaves the section honestly pending (rule 8).
    /// </summary>
    public void FillContent(string body, IEnumerable<BookQuestion> questions)
    {
        if (string.IsNullOrWhiteSpace(body))
            throw new DomainException("Section body must not be empty.");

        var questionList = questions?.ToList() ?? throw new DomainException("Questions must not be null.");
        if (questionList.Count != QuestionsPerSection)
            throw new DomainException($"A filled section must have exactly {QuestionsPerSection} questions.");

        Body = body.Trim();

        _questions.Clear();
        foreach (var question in questionList)
            _questions.Add(question ?? throw new DomainException("Question must not be null."));

        Status = BookSectionStatus.Filled;
    }

    public void AdminReplace(int order, string title, string body, IEnumerable<BookQuestion> questions)
    {
        if (order < 1) throw new DomainException("Section order must be positive.");
        if (string.IsNullOrWhiteSpace(title)) throw new DomainException("Section title must not be empty.");
        Order = order;
        Title = title.Trim();
        FillContent(body, questions);
    }

    /// <summary>
    /// Grades a learner's answers. Questions with no submitted answer count as incorrect, so the
    /// score reflects the whole quiz. A section passes at <see cref="BookQuizResult.PassThresholdPercent"/>
    /// correct answers (at least 70%).
    /// </summary>
    public BookQuizResult GradeQuiz(IReadOnlyDictionary<Guid, int> answers)
    {
        if (_questions.Count == 0)
            throw new DomainException("This section has no comprehension questions.");

        var outcomes = new List<BookQuestionOutcome>(_questions.Count);
        foreach (var question in _questions)
        {
            var hasAnswer = answers.TryGetValue(question.Id, out var selected);
            if (!hasAnswer)
                selected = -1;

            outcomes.Add(new BookQuestionOutcome(
                question.Id,
                selected,
                question.CorrectOptionIndex,
                hasAnswer && question.IsCorrect(selected),
                question.Explanation));
        }

        return new BookQuizResult(Id, _questions.Count, outcomes.Count(o => o.IsCorrect), outcomes);
    }
}
