namespace Domain.Writing;

/// <summary>
/// Lifecycle of a topic-scoped <see cref="WritingTask"/>. A task is created as a pending shell
/// bound to a learning-spine topic and becomes filled once its prompt + guidance are generated by
/// the LLM and cached (the same lazy-fill pattern as reading/grammar lessons).
/// </summary>
public enum WritingTaskStatus
{
    /// <summary>The prompt has not been generated yet (lazy-fill pending).</summary>
    Pending = 0,

    /// <summary>The prompt + guidance are generated and cached; the task is ready to write.</summary>
    Filled = 1,
}
