using Domain.Assessment;
using Domain.Common;

namespace Domain.Writing;

/// <summary>
/// A writing prompt (PROJECT-SPEC G.3). Every skill teaches the same learning-spine topics, so a
/// writing task is bound to a vocabulary topic and its prompt + guidance are generated by the LLM
/// on first open and cached (the lazy-fill pattern shared with reading/grammar lessons). The word
/// range follows the spec's per-level task types (A1-A2 short note, B1-B2 essay/letter, C1+
/// argumentative) and is fixed up front from the level. All learner-facing Uzbek text is resolved
/// from vetted templates (docs/development-guide.md rule 11); the English prompt + guidance are target-language
/// teaching content.
/// </summary>
public sealed class WritingTask
{
    private readonly List<string> _guidance = new();

    // Parameterless ctor for EF Core materialization.
    private WritingTask()
    {
        Prompt = null!;
    }

    private WritingTask(string prompt, CefrLevel level, int minWords, int maxWords, DateTimeOffset now)
    {
        Id = Guid.NewGuid();
        Prompt = prompt;
        Level = level;
        MinWords = minWords;
        MaxWords = maxWords;
        CreatedAt = now;
    }

    public Guid Id { get; private set; }

    /// <summary>
    /// The shared learning-spine topic this writing task teaches, when the task was created for a
    /// topic (the topic-scoped lazy-fill path). Null for legacy/standalone tasks (e.g. placement).
    /// </summary>
    public Guid? VocabularyTopicId { get; private set; }

    /// <summary>The English writing prompt shown to the learner; empty until the task is filled.</summary>
    public string Prompt { get; private set; }

    /// <summary>The curated CEFR level of the task.</summary>
    public CefrLevel Level { get; private set; }

    /// <summary>The minimum expected word count for this task's level.</summary>
    public int MinWords { get; private set; }

    /// <summary>The maximum expected word count for this task's level.</summary>
    public int MaxWords { get; private set; }

    /// <summary>Pending until the prompt + guidance are generated and cached.</summary>
    public WritingTaskStatus Status { get; private set; } = WritingTaskStatus.Filled;

    public DateTimeOffset CreatedAt { get; private set; }

    /// <summary>
    /// Short English "what to include" hints (immersion teaching support - sparser at higher
    /// levels). Empty for legacy tasks; populated by <see cref="FillContent"/> for topic tasks.
    /// </summary>
    public IReadOnlyList<string> Guidance => _guidance;

    /// <summary>True once the prompt content has been generated and cached.</summary>
    public bool IsFilled => Status == WritingTaskStatus.Filled;

    /// <summary>
    /// Builds a fully-specified task (prompt + word range known up front). Used by the placement
    /// stage and by tests; the topic-scoped catalog uses <see cref="ForTopic"/> + <see cref="FillContent"/>.
    /// </summary>
    public static WritingTask Create(
        string prompt, CefrLevel level, int minWords, int maxWords, DateTimeOffset now)
    {
        if (string.IsNullOrWhiteSpace(prompt))
            throw new DomainException("Writing prompt must not be empty.");
        if (minWords < 1)
            throw new DomainException("Minimum word count must be at least 1.");
        if (maxWords < minWords)
            throw new DomainException("Maximum word count must be at least the minimum.");

        return new WritingTask(prompt.Trim(), level, minWords, maxWords, now);
    }

    /// <summary>
    /// Creates a pending writing task bound to a learning-spine topic. The prompt + guidance are
    /// generated by the LLM on first open and cached via <see cref="FillContent"/> - the same
    /// lazy-fill pattern as a reading lesson (rules 8, 10). The word range is fixed up front from
    /// the level (the spec's per-level task types), so it is available even while pending.
    /// </summary>
    public static WritingTask ForTopic(
        Guid vocabularyTopicId, CefrLevel level, int minWords, int maxWords, DateTimeOffset now)
    {
        if (vocabularyTopicId == Guid.Empty)
            throw new DomainException("A topic-scoped task needs a vocabulary topic id.");
        if (minWords < 1)
            throw new DomainException("Minimum word count must be at least 1.");
        if (maxWords < minWords)
            throw new DomainException("Maximum word count must be at least the minimum.");

        return new WritingTask(string.Empty, level, minWords, maxWords, now)
        {
            VocabularyTopicId = vocabularyTopicId,
            Status = WritingTaskStatus.Pending,
        };
    }

    /// <summary>
    /// Stores the generated prompt and guidance, marking the task filled. Called once after the LLM
    /// produces the content; later reads serve the cache.
    /// </summary>
    public void FillContent(string prompt, IEnumerable<string> guidance)
    {
        if (string.IsNullOrWhiteSpace(prompt))
            throw new DomainException("Writing prompt must not be empty.");

        Prompt = prompt.Trim();

        _guidance.Clear();
        foreach (var hint in guidance ?? Enumerable.Empty<string>())
        {
            if (!string.IsNullOrWhiteSpace(hint))
                _guidance.Add(hint.Trim());
        }

        Status = WritingTaskStatus.Filled;
    }

    /// <summary>Number of words in a submitted text (whitespace-separated).</summary>
    public static int CountWords(string text) => string.IsNullOrWhiteSpace(text)
        ? 0
        : text.Split(new[] { ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries).Length;

    /// <summary>
    /// Admin create shell: a pending writing task with no topic and an empty prompt, whose word
    /// range is fixed up front from the level (PROJECT-SPEC G.3, the same per-level band the LLM
    /// lazy-fill path uses). The prompt is filled in later via <see cref="FillContent"/>.
    /// </summary>
    public static WritingTask CreateManual(CefrLevel level, DateTimeOffset now)
    {
        var (min, max) = WordRangeFor(level);
        return new WritingTask(string.Empty, level, min, max, now)
        {
            VocabularyTopicId = null,
            Status = WritingTaskStatus.Pending,
        };
    }

    /// <summary>
    /// Admin edit: re-binds the level and recomputes the word range from the level's per-level band.
    /// The prompt (if any) is left untouched.
    /// </summary>
    public void AdminUpdate(CefrLevel level)
    {
        Level = level;
        var (min, max) = WordRangeFor(level);
        MinWords = min;
        MaxWords = max;
    }

    /// <summary>
    /// The expected word range for a task at a given CEFR level - mirrors the Application-layer
    /// <c>WritingWordRange.For</c> (kept here so the Domain stays free of the Application dependency
    /// cycle). See WritingWordRange for the rationale behind each band.
    /// </summary>
    private static (int Min, int Max) WordRangeFor(CefrLevel level) => level switch
    {
        CefrLevel.A1 => (40, 70),
        CefrLevel.A2 => (50, 80),
        CefrLevel.B1 => (120, 200),
        CefrLevel.B2 => (150, 250),
        CefrLevel.C1 => (200, 300),
        _ => (250, 350),
    };
}
