using System.Text;
using Domain.Assessment;
using Domain.Vocabulary;

namespace Infrastructure.Vocabulary;

/// <summary>
/// The curated topic catalog - the single learning spine shared by every skill (PROJECT-SPEC
/// module 4): 50 distinct, level-appropriate topics for each CEFR level (A1–C2), 300 in total.
/// Each entry carries only its metadata - an English title, a vetted Uzbek label (rule 11), a
/// theme category and a grammar focus code; each skill's teaching content (passage, reading,
/// grammar lesson, listening transcript, writing prompt) is generated by the LLM on first open and
/// cached (rules 8, 10). Topics progress from concrete daily life (A1) to abstract, academic
/// themes (C2). 10 thematic categories × 5 topics = 50 per level.
/// </summary>
public static class VocabularyTopicCatalog
{
    private static readonly DateTimeOffset SeededAt = new(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);

    /// <summary>How many topics each thematic category contributes (10 categories × 5 = 50/level).</summary>
    public const int TopicsPerCategory = 5;

    /// <summary>
    /// Topics per CEFR level. Every skill (vocabulary, grammar, reading, listening, writing,
    /// speaking) teaches this same set of 50 topics per level - the shared learning spine.
    /// </summary>
    public const int TopicsPerLevel = 50;

    /// <summary>All 300 curated topics (50 per CEFR level), the spine shared by every skill.</summary>
    public static IReadOnlyList<VocabularyTopic> Topics()
    {
        var topics = new List<VocabularyTopic>(TopicsPerLevel * 6);
        AddLevel(topics, CefrLevel.A1, A1, A1Grammar);
        AddLevel(topics, CefrLevel.A2, A2, A2Grammar);
        AddLevel(topics, CefrLevel.B1, B1, B1Grammar);
        AddLevel(topics, CefrLevel.B2, B2, B2Grammar);
        AddLevel(topics, CefrLevel.C1, C1, C1Grammar);
        AddLevel(topics, CefrLevel.C2, C2, C2Grammar);
        return topics;
    }

    // Emits the first TopicsPerCategory topics of each category (the most fundamental ones), and
    // assigns each a grammar focus by cycling through the level's syllabus. With 50 topics and a
    // 10-code syllabus, every grammar point is taught in five different topic contexts - so the
    // 50 topics deterministically cover the level's whole CEFR grammar progression.
    //
    // The learning Sequence is simply the catalog declaration order: all five topics of the first
    // category, then all five of the next, and so on (a stable 0..49 progression). Every skill
    // reads the shared spine in this order, so the level roadmap (/levels) lists topics in the very
    // same category-by-category order in which the skill catalogs (vocabulary, speaking, …) group
    // them - one coherent, course-like order across all six modules.
    private static void AddLevel(
        List<VocabularyTopic> topics, CefrLevel level,
        (string Category, T[] Items)[] groups, string[] grammarSyllabus)
    {
        var focusCount = grammarSyllabus.Length;
        var index = 0;
        foreach (var (category, items) in groups)
            foreach (var item in items.Take(TopicsPerCategory))
            {
                // Grammar focus still cycles through the syllabus so every point recurs across five
                // topics - but it no longer drives the display order, only which lesson a topic uses.
                var focus = grammarSyllabus[index % focusCount];
                // Sequence follows declaration order so the spine reads category by category.
                var sequence = index;
                topics.Add(VocabularyTopic.Curate(
                    Slug(level, item.En), item.En, item.Uz, category, focus, level, SeededAt, sequence));
                index++;
            }
    }

    // ─── Per-level grammar syllabi (kebab-case focus codes). Cycled across each level's 50 topics
    //     so coverage is deterministic. The Grammar module resolves these codes to its 5-step
    //     lessons and vetted Uzbek explanation templates (rule 11). 10 codes/level → 5 contexts each.
    private static readonly string[] A1Grammar =
    {
        "to-be", "present-simple", "articles", "plural-nouns", "there-is-there-are",
        "possessive-adjectives", "prepositions-of-place", "can-ability", "present-continuous", "wh-questions",
    };

    private static readonly string[] A2Grammar =
    {
        "past-simple", "comparatives", "superlatives", "going-to-future", "adverbs-of-frequency",
        "countable-uncountable", "prepositions-of-time", "object-pronouns", "possessive-pronouns", "imperatives",
    };

    private static readonly string[] B1Grammar =
    {
        "present-perfect", "past-continuous", "first-conditional", "second-conditional", "gerunds-and-infinitives",
        "will-future", "modals-of-obligation", "defining-relative-clauses", "used-to", "comparative-adverbs",
    };

    private static readonly string[] B2Grammar =
    {
        "present-perfect-continuous", "past-perfect", "third-conditional", "passive-voice", "reported-speech",
        "modals-of-deduction", "non-defining-relative-clauses", "future-continuous", "wish-clauses", "causative-have",
    };

    private static readonly string[] C1Grammar =
    {
        "mixed-conditionals", "inversion", "cleft-sentences", "participle-clauses", "advanced-passive",
        "subjunctive", "future-perfect", "ellipsis-and-substitution", "nominalisation", "discourse-markers",
    };

    private static readonly string[] C2Grammar =
    {
        "hypothetical-meaning", "advanced-inversion", "fronting-and-emphasis", "cohesion-devices", "hedging-language",
        "emphatic-structures", "complex-reporting", "concessive-clauses", "idiomatic-modality", "register-and-formality",
    };

    /// <summary>A stable per-level slug (e.g. "a1-my-family"), unique across the whole catalog.</summary>
    private static string Slug(CefrLevel level, string title)
    {
        var sb = new StringBuilder(level.ToString().ToLowerInvariant());
        sb.Append('-');
        var lastDash = true;
        foreach (var c in title.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
                lastDash = false;
            }
            else if (!lastDash)
            {
                sb.Append('-');
                lastDash = true;
            }
        }

        return sb.ToString().TrimEnd('-');
    }

    /// <summary>An English title paired with its vetted Uzbek label.</summary>
    private readonly record struct T(string En, string Uz);

    private static (string, T[]) G(string category, params T[] items) => (category, items);

    // ───────────────────────────── A1 - concrete daily life ─────────────────────────────
    private static readonly (string, T[])[] A1 =
    {
        G("family_people",
            new("My Family", "Mening oilam"), new("My Mother", "Mening onam"),
            new("My Father", "Mening otam"), new("My Best Friend", "Eng yaqin do'stim"),
            new("My Baby Brother", "Kichkina ukam"), new("Our Neighbours", "Bizning qo'shnilarimiz"),
            new("My Grandparents", "Bobom va buvim"), new("People at Home", "Uydagi odamlar"),
            new("My Teacher", "Mening o'qituvchim"), new("My Classmates", "Sinfdoshlarim")),
        G("home_routine",
            new("My House", "Mening uyim"), new("My Bedroom", "Mening yotoqxonam"),
            new("My Morning", "Mening ertalabim"), new("Brushing My Teeth", "Tish yuvish"),
            new("Getting Dressed", "Kiyinish"), new("My Daily Routine", "Kunlik tartibim"),
            new("Cleaning My Room", "Xonamni tozalash"), new("Watching TV", "Televizor ko'rish"),
            new("Going to Bed", "Uyquga yotish"), new("My Weekend", "Mening dam olish kunim")),
        G("food_drink",
            new("Breakfast Time", "Nonushta vaqti"), new("My Favourite Fruit", "Sevimli mevam"),
            new("Vegetables", "Sabzavotlar"), new("Drinking Water", "Suv ichish"),
            new("A Cup of Tea", "Bir piyola choy"), new("Eating Lunch", "Tushlik qilish"),
            new("Sweets and Cakes", "Shirinliklar va tortlar"), new("Cooking with Mum", "Onam bilan ovqat pishirish"),
            new("At the Bakery", "Nonvoyxonada"), new("Dinner with Family", "Oila bilan kechki ovqat")),
        G("school",
            new("My School", "Mening maktabim"), new("My Schoolbag", "Mening sumkam"),
            new("In the Classroom", "Sinf xonasida"), new("My Pencil Case", "Qalamdonim"),
            new("Reading a Book", "Kitob o'qish"), new("Numbers One to Ten", "Birdan o'ngacha sonlar"),
            new("Colours", "Ranglar"), new("The Alphabet", "Alifbo"),
            new("My Homework", "Uy vazifam"), new("The School Bell", "Maktab qo'ng'irog'i")),
        G("animals_pets",
            new("My Cat", "Mening mushugim"), new("My Dog", "Mening itim"),
            new("Animals on the Farm", "Fermadagi hayvonlar"), new("Birds in the Garden", "Bog'dagi qushlar"),
            new("Fish in the Sea", "Dengizdagi baliqlar"), new("A Little Mouse", "Kichkina sichqon"),
            new("At the Zoo", "Hayvonot bog'ida"), new("Wild Animals", "Yovvoyi hayvonlar"),
            new("Baby Animals", "Hayvon bolalari"), new("My Pet Rabbit", "Mening quyonim")),
        G("body_health",
            new("My Body", "Mening tanam"), new("My Face", "Mening yuzim"),
            new("Washing My Hands", "Qo'l yuvish"), new("At the Doctor", "Shifokorda"),
            new("I Feel Sick", "Men kasal bo'ldim"), new("Brushing My Hair", "Soch tarash"),
            new("My Two Hands", "Ikki qo'lim"), new("Healthy Teeth", "Sog'lom tishlar"),
            new("Sleeping Well", "Yaxshi uxlash"), new("Catching a Cold", "Shamollab qolish")),
        G("clothes_weather",
            new("My Clothes", "Mening kiyimlarim"), new("A Rainy Day", "Yomg'irli kun"),
            new("A Sunny Day", "Quyoshli kun"), new("Winter Clothes", "Qishki kiyimlar"),
            new("My Shoes", "Mening poyabzalim"), new("Snow in Winter", "Qishdagi qor"),
            new("A Windy Day", "Shamolli kun"), new("My Favourite Hat", "Sevimli shlyapam"),
            new("Summer Days", "Yozgi kunlar"), new("A Cloudy Sky", "Bulutli osmon")),
        G("places_town",
            new("The Park", "Bog'"), new("The Shop", "Do'kon"),
            new("The Bus Stop", "Avtobus bekati"), new("The Market", "Bozor"),
            new("My Street", "Mening ko'cham"), new("The Playground", "O'yin maydoni"),
            new("The Library", "Kutubxona"), new("The Hospital", "Kasalxona"),
            new("The Post Office", "Pochta bo'limi"), new("The Train Station", "Temir yo'l bekati")),
        G("free_time_toys",
            new("My Toys", "Mening o'yinchoqlarim"), new("Playing Football", "Futbol o'ynash"),
            new("Riding a Bike", "Velosiped haydash"), new("My Ball", "Mening to'pim"),
            new("Drawing Pictures", "Rasm chizish"), new("Playing Games", "O'yin o'ynash"),
            new("My Favourite Toy", "Sevimli o'yinchog'im"), new("Singing Songs", "Qo'shiq aytish"),
            new("Dancing", "Raqs tushish"), new("Building Blocks", "Konstruktor yig'ish")),
        G("time_numbers",
            new("Days of the Week", "Hafta kunlari"), new("Months of the Year", "Yil oylari"),
            new("Telling the Time", "Vaqtni aytish"), new("My Birthday", "Mening tug'ilgan kunim"),
            new("Counting to Twenty", "Yigirmagacha sanash"), new("Big and Small", "Katta va kichik"),
            new("Shapes Around Us", "Atrofimizdagi shakllar"), new("My Favourite Colour", "Sevimli rangim"),
            new("Morning and Night", "Ertalab va kechasi"), new("The Four Seasons", "To'rt fasl")),
    };

    // ───────────────────────────── A2 - everyday life, broader ─────────────────────────────
    private static readonly (string, T[])[] A2 =
    {
        G("daily_life",
            new("A Busy Morning", "Tashvishli ertalab"), new("After School", "Maktabdan keyin"),
            new("Helping at Home", "Uy ishlariga yordam"), new("My Free Day", "Bo'sh kunim"),
            new("Making Plans", "Reja tuzish"), new("A Day Off", "Dam olish kuni"),
            new("My Evening Routine", "Kechki tartibim"), new("Waking Up Early", "Erta turish"),
            new("A Family Outing", "Oilaviy sayohat"), new("Visiting Relatives", "Qarindoshlarni ziyorat qilish")),
        G("food_eating_out",
            new("At a Restaurant", "Restoranda"), new("Ordering Food", "Ovqat buyurtma qilish"),
            new("My Favourite Meal", "Sevimli taomim"), new("Healthy Eating", "Sog'lom ovqatlanish"),
            new("A Cooking Recipe", "Ovqat retsepti"), new("At the Cafe", "Kafeda"),
            new("Buying Groceries", "Oziq-ovqat xarid qilish"), new("A Picnic in the Park", "Bog'da piknik"),
            new("Street Food", "Ko'cha taomlari"), new("Breakfast Around the World", "Dunyo bo'ylab nonushta")),
        G("travel_transport",
            new("Taking the Bus", "Avtobusda yurish"), new("A Train Journey", "Poyezd sayohati"),
            new("At the Airport", "Aeroportda"), new("Asking for Directions", "Yo'l so'rash"),
            new("My First Trip", "Birinchi sayohatim"), new("Packing a Suitcase", "Chamadon yig'ish"),
            new("A Day at the Beach", "Plyajdagi kun"), new("Riding the Metro", "Metroda yurish"),
            new("A Holiday Plan", "Ta'til rejasi"), new("Lost in the City", "Shaharda adashish")),
        G("shopping",
            new("At the Supermarket", "Supermarketda"), new("Buying Clothes", "Kiyim sotib olish"),
            new("Paying with Money", "Pul bilan to'lash"), new("A Shopping List", "Xarid ro'yxati"),
            new("Looking for a Gift", "Sovg'a izlash"), new("At the Shoe Shop", "Poyabzal do'konida"),
            new("Prices and Sales", "Narxlar va chegirmalar"), new("Online Shopping", "Onlayn xarid"),
            new("Returning an Item", "Mahsulotni qaytarish"), new("At the Pharmacy", "Dorixonada")),
        G("work_jobs",
            new("Jobs People Do", "Odamlar bajaradigan kasblar"), new("A Day at Work", "Ishdagi kun"),
            new("My Dream Job", "Orzuyimdagi kasb"), new("At the Office", "Ofisda"),
            new("A Helpful Doctor", "Yordamchi shifokor"), new("The Bus Driver", "Avtobus haydovchisi"),
            new("Working in a Shop", "Do'konda ishlash"), new("A Busy Farmer", "Tashvishli dehqon"),
            new("The Firefighter", "O't o'chiruvchi"), new("Working from Home", "Uydan ishlash")),
        G("health_body",
            new("Going to the Dentist", "Tish shifokoriga borish"), new("Staying Healthy", "Sog'lom bo'lish"),
            new("A Visit to the Doctor", "Shifokorga tashrif"), new("Doing Exercise", "Mashq qilish"),
            new("Getting Enough Sleep", "Yetarli uxlash"), new("A Healthy Breakfast", "Sog'lom nonushta"),
            new("When I Am Ill", "Kasal bo'lganimda"), new("Washing and Hygiene", "Yuvinish va gigiena"),
            new("Drinking Enough Water", "Yetarli suv ichish"), new("A Walk in the Morning", "Ertalabki sayr")),
        G("hobbies_free_time",
            new("My Hobby", "Mening sevimli mashg'ulotim"), new("Playing Music", "Musiqa chalish"),
            new("Watching a Film", "Film ko'rish"), new("Reading for Fun", "Zavq uchun o'qish"),
            new("Taking Photos", "Surat olish"), new("Going Swimming", "Suzishga borish"),
            new("Playing Computer Games", "Kompyuter o'yinlari"), new("Collecting Things", "Narsalar to'plash"),
            new("Gardening", "Bog'dorchilik"), new("A Sports Club", "Sport to'garagi")),
        G("town_directions",
            new("In My Town", "Mening shahrimda"), new("Finding the Bank", "Bankni topish"),
            new("Crossing the Road", "Yo'lni kesib o'tish"), new("At the Museum", "Muzeyda"),
            new("A Map of the City", "Shahar xaritasi"), new("Around the Neighbourhood", "Mahalla atrofida"),
            new("The City Centre", "Shahar markazi"), new("Places to Visit", "Borib ko'riladigan joylar"),
            new("Public Transport", "Jamoat transporti"), new("A New Building", "Yangi bino")),
        G("weather_seasons",
            new("Spring Has Come", "Bahor keldi"), new("A Hot Summer", "Issiq yoz"),
            new("Autumn Leaves", "Kuzgi barglar"), new("A Cold Winter", "Sovuq qish"),
            new("Today's Weather", "Bugungi ob-havo"), new("A Storm Is Coming", "Bo'ron yaqinlashmoqda"),
            new("Clothes for the Weather", "Ob-havoga mos kiyim"), new("Rain and Umbrellas", "Yomg'ir va soyabonlar"),
            new("The Weather Forecast", "Ob-havo bashorati"), new("My Favourite Season", "Sevimli faslim")),
        G("home_technology",
            new("Using a Phone", "Telefondan foydalanish"), new("My Computer", "Mening kompyuterim"),
            new("Sending a Message", "Xabar yuborish"), new("Taking a Selfie", "Selfi olish"),
            new("Watching Videos Online", "Onlayn video ko'rish"), new("A Useful App", "Foydali ilova"),
            new("Charging My Phone", "Telefonni quvvatlash"), new("Listening to Music", "Musiqa tinglash"),
            new("A Video Call", "Video qo'ng'iroq"), new("Saving Photos", "Suratlarni saqlash")),
    };

    // ───────────────────────────── B1 - opinions & experiences ─────────────────────────────
    private static readonly (string, T[])[] B1 =
    {
        G("travel_culture",
            new("Travelling Alone", "Yolg'iz sayohat qilish"), new("Different Cultures", "Turli madaniyatlar"),
            new("A Memorable Holiday", "Esda qolarli ta'til"), new("Living Abroad", "Chet elda yashash"),
            new("Festivals Around the World", "Dunyo bayramlari"), new("Learning a New Language", "Yangi til o'rganish"),
            new("Tourist Attractions", "Sayyohlik joylari"), new("A Cultural Misunderstanding", "Madaniy tushunmovchilik"),
            new("Budget Travel", "Tejamkor sayohat"), new("The Best Way to Travel", "Sayohatning eng yaxshi usuli")),
        G("work_career",
            new("Choosing a Career", "Kasb tanlash"), new("A Job Interview", "Ish suhbati"),
            new("Working in a Team", "Jamoada ishlash"), new("My Future Plans", "Kelajak rejalarim"),
            new("Part-Time Jobs", "Yarim stavka ishlar"), new("A Good Boss", "Yaxshi rahbar"),
            new("Work and Stress", "Ish va stress"), new("Starting a Business", "Biznes boshlash"),
            new("Skills for the Job", "Ish uchun ko'nikmalar"), new("Working Late", "Kech qolib ishlash")),
        G("education_learning",
            new("Studying for Exams", "Imtihonlarga tayyorlanish"), new("Online Learning", "Onlayn ta'lim"),
            new("A Good Teacher", "Yaxshi o'qituvchi"), new("University Life", "Universitet hayoti"),
            new("Learning from Mistakes", "Xatolardan o'rganish"), new("Homework Habits", "Uy vazifasi odatlari"),
            new("School Subjects", "Maktab fanlari"), new("A School Trip", "Maktab ekskursiyasi"),
            new("Reading Books", "Kitob o'qish"), new("Studying Abroad", "Chet elda o'qish")),
        G("health_lifestyle",
            new("A Balanced Diet", "Muvozanatli ovqatlanish"), new("Keeping Fit", "Jismonan tetik bo'lish"),
            new("Stress and Relaxation", "Stress va dam olish"), new("Healthy Habits", "Sog'lom odatlar"),
            new("Too Much Screen Time", "Ekran oldida ko'p vaqt"), new("Going to the Gym", "Sport zaliga borish"),
            new("Sleep and Energy", "Uyqu va energiya"), new("Giving Up Bad Habits", "Yomon odatlardan voz kechish"),
            new("Mental Health", "Ruhiy salomatlik"), new("A Healthy Lifestyle", "Sog'lom turmush tarzi")),
        G("environment_nature",
            new("Saving Water", "Suvni tejash"), new("Recycling at Home", "Uyda qayta ishlash"),
            new("Climate Change", "Iqlim o'zgarishi"), new("Protecting Animals", "Hayvonlarni himoya qilish"),
            new("Air Pollution", "Havo ifloslanishi"), new("Planting Trees", "Daraxt ekish"),
            new("Life in the Countryside", "Qishloq hayoti"), new("Natural Disasters", "Tabiiy ofatlar"),
            new("Renewable Energy", "Qayta tiklanuvchi energiya"), new("Keeping the City Clean", "Shaharni toza tutish")),
        G("technology_internet",
            new("Social Media", "Ijtimoiy tarmoqlar"), new("Life Without the Internet", "Internetsiz hayot"),
            new("Smartphones Everywhere", "Hamma joyda smartfonlar"), new("Shopping Online", "Onlayn xarid qilish"),
            new("Staying Safe Online", "Internetda xavfsizlik"), new("Useful Gadgets", "Foydali qurilmalar"),
            new("Video Games", "Video o'yinlar"), new("Working with Computers", "Kompyuterlar bilan ishlash"),
            new("The News Online", "Onlayn yangiliklar"), new("Too Connected", "Haddan tashqari bog'liqlik")),
        G("money_shopping",
            new("Saving Money", "Pul tejash"), new("Spending Wisely", "Oqilona xarajat"),
            new("Pocket Money", "Cho'ntak puli"), new("Expensive and Cheap", "Qimmat va arzon"),
            new("A New Phone", "Yangi telefon"), new("Borrowing and Lending", "Qarz olish va berish"),
            new("Shopping Habits", "Xarid odatlari"), new("A Good Bargain", "Yaxshi savdo"),
            new("Paying by Card", "Karta bilan to'lash"), new("Planning a Budget", "Byudjet rejalashtirish")),
        G("media_entertainment",
            new("My Favourite Film", "Sevimli filmim"), new("Watching the News", "Yangiliklarni ko'rish"),
            new("A Great Concert", "Ajoyib konsert"), new("Books or Films", "Kitoblar yoki filmlar"),
            new("Listening to Podcasts", "Podkast tinglash"), new("A TV Series", "Teleserial"),
            new("Live Sport", "Jonli sport"), new("Music Festivals", "Musiqa festivallari"),
            new("Becoming Famous", "Mashhur bo'lish"), new("Advertising on TV", "Televizordagi reklama")),
        G("relationships_society",
            new("Making New Friends", "Yangi do'st orttirish"), new("Family Traditions", "Oilaviy an'analar"),
            new("Helping Others", "Boshqalarga yordam berish"), new("Living in a City", "Shaharda yashash"),
            new("Good Manners", "Yaxshi xulq"), new("Volunteering", "Ko'ngillilik faoliyati"),
            new("Neighbours and Community", "Qo'shnilar va jamoa"), new("Growing Up", "Ulg'ayish"),
            new("Keeping in Touch", "Aloqada bo'lish"), new("A Special Celebration", "Maxsus bayram")),
        G("city_life",
            new("Rush Hour", "Tirbandlik vaqti"), new("City or Village", "Shahar yoki qishloq"),
            new("Public Parks", "Jamoat bog'lari"), new("Traffic Problems", "Yo'l harakati muammolari"),
            new("Modern Buildings", "Zamonaviy binolar"), new("Getting Around Town", "Shaharda harakatlanish"),
            new("Noise in the City", "Shahardagi shovqin"), new("A Growing City", "O'sib borayotgan shahar"),
            new("Safe Streets", "Xavfsiz ko'chalar"), new("Life in the Suburbs", "Chekka hududlardagi hayot")),
    };

    // ───────────────────────────── B2 - abstract & discursive ─────────────────────────────
    private static readonly (string, T[])[] B2 =
    {
        G("society_issues",
            new("The Generation Gap", "Avlodlar o'rtasidagi tafovut"), new("Equality and Fairness", "Tenglik va adolat"),
            new("Urban Migration", "Shaharga ko'chish"), new("Work-Life Balance", "Ish va hayot muvozanati"),
            new("The Cost of Living", "Yashash qiymati"), new("Social Inequality", "Ijtimoiy tengsizlik"),
            new("Changing Family Structures", "O'zgaruvchan oila tuzilmalari"), new("Community Spirit", "Jamoa ruhi"),
            new("An Ageing Population", "Qariyotgan aholi"), new("The Value of Volunteering", "Ko'ngillilikning qadri")),
        G("science_innovation",
            new("Space Exploration", "Koinotni o'rganish"), new("Medical Breakthroughs", "Tibbiy yutuqlar"),
            new("The Future of Robots", "Robotlar kelajagi"), new("Scientific Curiosity", "Ilmiy qiziquvchanlik"),
            new("Genetics and DNA", "Genetika va DNK"), new("How Vaccines Work", "Vaksinalar qanday ishlaydi"),
            new("Renewable Technology", "Qayta tiklanuvchi texnologiya"), new("The Power of Experiments", "Tajribalarning kuchi"),
            new("Artificial Materials", "Sun'iy materiallar"), new("Exploring the Oceans", "Okeanlarni o'rganish")),
        G("environment_sustainability",
            new("Plastic Pollution", "Plastik ifloslanish"), new("Sustainable Living", "Barqaror hayot"),
            new("The Energy Crisis", "Energiya inqirozi"), new("Protecting Forests", "O'rmonlarni asrash"),
            new("Global Warming", "Global isish"), new("Green Cities", "Yashil shaharlar"),
            new("Saving Endangered Species", "Yo'qolib borayotgan turlarni saqlash"), new("Food Waste", "Oziq-ovqat isrofi"),
            new("Clean Transport", "Toza transport"), new("The Carbon Footprint", "Uglerod izi")),
        G("work_economy",
            new("The Gig Economy", "Erkin mehnat iqtisodiyoti"), new("Automation and Jobs", "Avtomatlashtirish va ishlar"),
            new("Entrepreneurship", "Tadbirkorlik"), new("Job Satisfaction", "Ishdan qoniqish"),
            new("Remote Working", "Masofadan ishlash"), new("Money and Happiness", "Pul va baxt"),
            new("Global Trade", "Global savdo"), new("Small Businesses", "Kichik bizneslar"),
            new("Workplace Culture", "Ish joyidagi madaniyat"), new("The Future of Money", "Pul kelajagi")),
        G("education_knowledge",
            new("Lifelong Learning", "Umrbod ta'lim"), new("Exams or Projects", "Imtihonlar yoki loyihalar"),
            new("The Value of Reading", "O'qishning qadri"), new("Learning Styles", "O'rganish uslublari"),
            new("Education and Technology", "Ta'lim va texnologiya"), new("Critical Thinking", "Tanqidiy fikrlash"),
            new("The Purpose of School", "Maktabning maqsadi"), new("Studying Languages", "Tillarni o'rganish"),
            new("Self-Education", "O'z-o'zini tarbiyalash"), new("Knowledge and Wisdom", "Bilim va donolik")),
        G("health_psychology",
            new("The Science of Sleep", "Uyqu ilmi"), new("Managing Stress", "Stressni boshqarish"),
            new("Happiness and Habits", "Baxt va odatlar"), new("The Power of Exercise", "Mashqning kuchi"),
            new("Diet and Health", "Parhez va salomatlik"), new("Emotions and the Brain", "Hissiyotlar va miya"),
            new("Mindfulness", "Ongli yashash"), new("Why We Procrastinate", "Nega ishni keyinga suramiz"),
            new("Building Confidence", "Ishonch shakllantirish"), new("Healthy Relationships", "Sog'lom munosabatlar")),
        G("media_communication",
            new("Fake News", "Yolg'on yangiliklar"), new("The Power of Advertising", "Reklamaning kuchi"),
            new("Social Media and Identity", "Ijtimoiy tarmoq va shaxsiyat"), new("Freedom of Speech", "So'z erkinligi"),
            new("Influencers", "Ta'sirchi shaxslar"), new("Privacy Online", "Internetdagi maxfiylik"),
            new("The Future of Journalism", "Jurnalistika kelajagi"), new("Memes and Culture", "Memlar va madaniyat"),
            new("Body Language", "Tana tili"), new("Communicating Across Cultures", "Madaniyatlararo muloqot")),
        G("culture_arts",
            new("The Role of Art", "San'atning roli"), new("Music and Emotion", "Musiqa va hissiyot"),
            new("Modern Cinema", "Zamonaviy kino"), new("Preserving Traditions", "An'analarni saqlash"),
            new("Architecture and Design", "Arxitektura va dizayn"), new("Street Art", "Ko'cha san'ati"),
            new("Literature and Society", "Adabiyot va jamiyat"), new("The Beauty of Languages", "Tillarning go'zalligi"),
            new("Cultural Identity", "Madaniy o'ziga xoslik"), new("Fashion and Self-Expression", "Moda va o'zini ifodalash")),
        G("technology_future",
            new("Living with AI", "Sun'iy intellekt bilan yashash"), new("Smart Homes", "Aqlli uylar"),
            new("Self-Driving Cars", "O'zi yuradigan mashinalar"), new("Virtual Reality", "Virtual reallik"),
            new("The Internet of Things", "Narsalar interneti"), new("Digital Privacy", "Raqamli maxfiylik"),
            new("The Future of Work", "Mehnat kelajagi"), new("Technology and Children", "Texnologiya va bolalar"),
            new("Wearable Technology", "Kiyiladigan texnologiya"), new("A Cashless Society", "Naqdsiz jamiyat")),
        G("global_issues",
            new("Poverty and Hunger", "Qashshoqlik va ochlik"), new("Human Rights", "Inson huquqlari"),
            new("Global Health", "Global salomatlik"), new("Migration and Refugees", "Migratsiya va qochqinlar"),
            new("World Peace", "Jahon tinchligi"), new("Access to Education", "Ta'limga kirish imkoniyati"),
            new("Clean Water for All", "Hamma uchun toza suv"), new("International Cooperation", "Xalqaro hamkorlik"),
            new("The Digital Divide", "Raqamli tafovut"), new("Responsible Tourism", "Mas'uliyatli sayyohlik")),
    };

    // ───────────────────────────── C1 - analytical & academic ─────────────────────────────
    private static readonly (string, T[])[] C1 =
    {
        G("politics_governance",
            new("Democracy and Its Limits", "Demokratiya va uning chegaralari"), new("The Role of Government", "Hukumatning roli"),
            new("Public Policy", "Davlat siyosati"), new("Civic Participation", "Fuqarolik ishtiroki"),
            new("Power and Accountability", "Hokimiyat va javobgarlik"), new("Political Polarisation", "Siyosiy tarqoqlik"),
            new("The Welfare State", "Ijtimoiy himoya davlati"), new("Corruption and Transparency", "Korruptsiya va shaffoflik"),
            new("Nationalism and Identity", "Millatchilik va o'ziga xoslik"), new("The Future of Voting", "Ovoz berish kelajagi")),
        G("economics_markets",
            new("Inflation Explained", "Inflyatsiya tushuntirilishi"), new("Supply and Demand", "Talab va taklif"),
            new("The Stock Market", "Fond bozori"), new("Globalisation of Trade", "Savdoning globallashuvi"),
            new("Income Inequality", "Daromad tengsizligi"), new("The Future of Currency", "Valyuta kelajagi"),
            new("Consumer Behaviour", "Iste'molchi xulqi"), new("Economic Growth", "Iqtisodiy o'sish"),
            new("The Cost of Debt", "Qarz qiymati"), new("Markets and Morality", "Bozorlar va axloq")),
        G("science_research",
            new("The Scientific Method", "Ilmiy metod"), new("Quantum Physics", "Kvant fizikasi"),
            new("The Origins of Life", "Hayot kelib chiqishi"), new("Climate Modelling", "Iqlim modellashtirish"),
            new("The Human Genome", "Inson genomi"), new("Dark Matter", "Qorong'u materiya"),
            new("Evolutionary Biology", "Evolyutsion biologiya"), new("The Limits of Knowledge", "Bilim chegaralari"),
            new("Funding Research", "Tadqiqotlarni moliyalashtirish"), new("Science and Society", "Fan va jamiyat")),
        G("philosophy_ethics",
            new("What Is Justice", "Adolat nima"), new("Free Will", "Iroda erkinligi"),
            new("The Meaning of Happiness", "Baxtning ma'nosi"), new("Moral Dilemmas", "Axloqiy dilemmalar"),
            new("The Ethics of Technology", "Texnologiya axloqi"), new("Truth and Belief", "Haqiqat va e'tiqod"),
            new("The Nature of Consciousness", "Ong tabiati"), new("Rights and Responsibilities", "Huquqlar va majburiyatlar"),
            new("The Good Life", "Yaxshi hayot"), new("Ends and Means", "Maqsad va vositalar")),
        G("globalisation_society",
            new("A Connected World", "Bog'langan dunyo"), new("Cultural Homogenisation", "Madaniy bir xillashuv"),
            new("Global Supply Chains", "Global ta'minot zanjirlari"), new("The Spread of Ideas", "G'oyalarning tarqalishi"),
            new("Local versus Global", "Mahalliy va global"), new("Diaspora Communities", "Diaspora jamoalari"),
            new("Soft Power", "Yumshoq kuch"), new("The English Language Worldwide", "Ingliz tili dunyo bo'ylab"),
            new("Borders and Belonging", "Chegaralar va mansublik"), new("Global Citizenship", "Global fuqarolik")),
        G("technology_ai",
            new("Machine Learning", "Mashinali o'rganish"), new("Algorithms and Bias", "Algoritmlar va xolislik yo'qligi"),
            new("The Ethics of AI", "Sun'iy intellekt axloqi"), new("Big Data", "Katta ma'lumotlar"),
            new("Automation and Society", "Avtomatlashtirish va jamiyat"), new("Surveillance Technology", "Kuzatuv texnologiyasi"),
            new("Human and Machine", "Inson va mashina"), new("The Singularity", "Singulyarlik"),
            new("Digital Identity", "Raqamli shaxsiyat"), new("Trust in Technology", "Texnologiyaga ishonch")),
        G("environment_policy",
            new("Carbon Taxes", "Uglerod soliqlari"), new("The Paris Agreement", "Parij kelishuvi"),
            new("Sustainable Development", "Barqaror rivojlanish"), new("Biodiversity Loss", "Bioxilma-xillik yo'qolishi"),
            new("The Circular Economy", "Aylanma iqtisodiyot"), new("Environmental Justice", "Ekologik adolat"),
            new("Geoengineering", "Geomuhandislik"), new("Water Scarcity", "Suv tanqisligi"),
            new("The Politics of Climate", "Iqlim siyosati"), new("Green Innovation", "Yashil innovatsiya")),
        G("culture_identity",
            new("Language and Thought", "Til va tafakkur"), new("Heritage and Memory", "Meros va xotira"),
            new("Multiculturalism", "Ko'p madaniyatlilik"), new("The Construction of Identity", "Shaxsiyatning shakllanishi"),
            new("Tradition versus Modernity", "An'ana va zamonaviylik"), new("Art as Resistance", "San'at qarshilik sifatida"),
            new("Gender and Society", "Jins va jamiyat"), new("The Globalised Self", "Globallashgan shaxs"),
            new("Storytelling and Culture", "Hikoya va madaniyat"), new("Cultural Appropriation", "Madaniy o'zlashtirish")),
        G("law_justice",
            new("The Rule of Law", "Qonun ustuvorligi"), new("Crime and Punishment", "Jinoyat va jazo"),
            new("Human Rights Law", "Inson huquqlari qonuni"), new("Justice and Mercy", "Adolat va rahm"),
            new("The Right to Privacy", "Maxfiylik huquqi"), new("Courts and Fairness", "Sudlar va adolat"),
            new("Civil Disobedience", "Fuqarolik itoatsizligi"), new("Intellectual Property", "Intellektual mulk"),
            new("International Law", "Xalqaro huquq"), new("Justice in the Digital Age", "Raqamli davrda adolat")),
        G("business_leadership",
            new("What Makes a Leader", "Yetakchini nima qiladi"), new("Innovation in Business", "Bizensdagi innovatsiya"),
            new("Corporate Responsibility", "Korporativ mas'uliyat"), new("Negotiation Skills", "Muzokara ko'nikmalari"),
            new("Building a Brand", "Brend yaratish"), new("Risk and Reward", "Tavakkal va mukofot"),
            new("Managing Change", "O'zgarishlarni boshqarish"), new("The Start-Up World", "Startaplar dunyosi"),
            new("Ethical Business", "Axloqiy biznes"), new("Failure and Success", "Muvaffaqiyatsizlik va muvaffaqiyat")),
    };

    // ───────────────────────────── C2 - nuanced & specialist ─────────────────────────────
    private static readonly (string, T[])[] C2 =
    {
        G("geopolitics_diplomacy",
            new("The Balance of Power", "Kuchlar muvozanati"), new("Diplomacy and Negotiation", "Diplomatiya va muzokara"),
            new("Sovereignty in a Globalised World", "Globallashgan dunyoda suverenitet"), new("Economic Sanctions", "Iqtisodiy sanksiyalar"),
            new("Regional Alliances", "Mintaqaviy ittifoqlar"), new("The Geopolitics of Energy", "Energiya geosiyosati"),
            new("Conflict and Resolution", "Mojaro va uni hal etish"), new("Hard and Soft Power", "Qattiq va yumshoq kuch"),
            new("Global Governance", "Global boshqaruv"), new("The New World Order", "Yangi jahon tartibi")),
        G("macroeconomics_finance",
            new("Monetary Policy", "Pul-kredit siyosati"), new("Fiscal Stimulus", "Fiskal rag'batlantirish"),
            new("Financial Crises", "Moliyaviy inqirozlar"), new("Central Banking", "Markaziy bank faoliyati"),
            new("The Bond Market", "Obligatsiyalar bozori"), new("Cryptocurrency and Regulation", "Kriptovalyuta va tartibga solish"),
            new("Sovereign Debt", "Davlat qarzi"), new("Behavioural Economics", "Xulq-atvor iqtisodiyoti"),
            new("Quantitative Easing", "Miqdoriy yumshatish"), new("The Future of Capitalism", "Kapitalizm kelajagi")),
        G("epistemology_philosophy",
            new("The Theory of Knowledge", "Bilim nazariyasi"), new("Scepticism and Certainty", "Skeptitsizm va ishonchlilik"),
            new("Rationalism and Empiricism", "Ratsionalizm va empirizm"), new("The Problem of Induction", "Induksiya muammosi"),
            new("Language and Meaning", "Til va ma'no"), new("The Limits of Reason", "Aql chegaralari"),
            new("Objectivity and Bias", "Obyektivlik va tarafkashlik"), new("Truth and Relativism", "Haqiqat va relyativizm"),
            new("The Mind-Body Problem", "Tan-ong muammosi"), new("Knowledge in the Digital Age", "Raqamli davrda bilim")),
        G("neuroscience_cognition",
            new("How Memory Works", "Xotira qanday ishlaydi"), new("The Neuroscience of Decision", "Qaror qabul qilish neyrofani"),
            new("Attention and Focus", "Diqqat va e'tibor"), new("The Plastic Brain", "Moslashuvchan miya"),
            new("Consciousness and the Self", "Ong va o'zlik"), new("Emotion and Reason", "Hissiyot va aql"),
            new("Cognitive Biases", "Kognitiv xatoliklar"), new("Language in the Brain", "Miyadagi til"),
            new("Learning and the Brain", "O'rganish va miya"), new("The Limits of Perception", "Idrok chegaralari")),
        G("bioethics_medicine",
            new("Gene Editing", "Genlarni tahrirlash"), new("The Ethics of Cloning", "Klonlash axloqi"),
            new("End-of-Life Care", "Umr oxiridagi parvarish"), new("Medical Confidentiality", "Tibbiy maxfiylik"),
            new("Access to Healthcare", "Sog'liqni saqlashga kirish"), new("Pandemics and Society", "Pandemiyalar va jamiyat"),
            new("Personalised Medicine", "Shaxsiylashtirilgan tibbiyot"), new("The Right to Die", "O'lish huquqi"),
            new("Organ Transplantation", "A'zolarni transplantatsiya qilish"), new("AI in Diagnosis", "Tashxisda sun'iy intellekt")),
        G("linguistics_language",
            new("How Languages Change", "Tillar qanday o'zgaradi"), new("Language and Power", "Til va hokimiyat"),
            new("The Origins of Language", "Til kelib chiqishi"), new("Bilingualism", "Ikki tillilik"),
            new("Endangered Languages", "Yo'qolib borayotgan tillar"), new("Dialect and Identity", "Dialekt va o'ziga xoslik"),
            new("The Politics of Spelling", "Imlo siyosati"), new("Translation and Meaning", "Tarjima va ma'no"),
            new("Language Acquisition", "Tilni egallash"), new("The Future of English", "Ingliz tili kelajagi")),
        G("sustainability_climate",
            new("Tipping Points", "O'zgarish nuqtalari"), new("Decarbonisation", "Dekarbonizatsiya"),
            new("Climate Adaptation", "Iqlimga moslashish"), new("The Economics of Climate Change", "Iqlim o'zgarishi iqtisodiyoti"),
            new("Loss and Damage", "Yo'qotish va zarar"), new("Planetary Boundaries", "Sayyora chegaralari"),
            new("Just Transition", "Adolatli o'tish"), new("Carbon Markets", "Uglerod bozorlari"),
            new("Rewilding", "Tabiatni tiklash"), new("The Anthropocene", "Antroposen davri")),
        G("innovation_disruption",
            new("Disruptive Technology", "Buzg'unchi texnologiya"), new("The Innovation Economy", "Innovatsiya iqtisodiyoti"),
            new("Platform Monopolies", "Platforma monopoliyalari"), new("The Attention Economy", "Diqqat iqtisodiyoti"),
            new("Network Effects", "Tarmoq effektlari"), new("Creative Destruction", "Ijodiy yemirilish"),
            new("Open Source", "Ochiq manba"), new("The Productivity Paradox", "Unumdorlik paradoksi"),
            new("Scaling a Company", "Kompaniyani kengaytirish"), new("Technology and Inequality", "Texnologiya va tengsizlik")),
        G("jurisprudence_rights",
            new("Natural Law", "Tabiiy huquq"), new("Constitutional Rights", "Konstitutsiyaviy huquqlar"),
            new("The Limits of Free Speech", "So'z erkinligi chegaralari"), new("Justice and the State", "Adolat va davlat"),
            new("Privacy versus Security", "Maxfiylik va xavfsizlik"), new("The Death Penalty", "O'lim jazosi"),
            new("Rights of Future Generations", "Kelajak avlodlar huquqlari"), new("Law and Technology", "Huquq va texnologiya"),
            new("Restorative Justice", "Tiklovchi adolat"), new("The Social Contract", "Ijtimoiy shartnoma")),
        G("aesthetics_theory",
            new("What Is Beauty", "Go'zallik nima"), new("The Purpose of Art", "San'at maqsadi"),
            new("High and Low Culture", "Yuksak va ommaviy madaniyat"), new("The Author and the Text", "Muallif va matn"),
            new("Art and the Market", "San'at va bozor"), new("Taste and Judgement", "Did va hukm"),
            new("The Sublime", "Ulug'vorlik"), new("Originality and Imitation", "Asllik va taqlid"),
            new("Criticism and Interpretation", "Tanqid va talqin"), new("Art in the Age of Reproduction", "Nusxa ko'paytirish davrida san'at")),
    };
}
